### ISSUE TITLE
Please kindly take the main xarchiver project over at sf.net and sync it 

### ISSUE THREAD

**Issue by ketetefid** [ib/xarchiver#10]
As a lot of distros and repositories still make xarchiver from its old place i.e. http://xarchiver.sourceforge.net/
please take over the project there and synchronize both places. The former developer has already declared that he is looking for a substitute: https://sourceforge.net/p/xarchiver/bugs/93/

Regards

**Comment by ib** [comment]
I have no interest in working on SourceForge.

If the former developer wants to pass the project, he should close the project there and make users aware of the active continuation of the project here.
