### ISSUE TITLE
Large archives crash xarchiver when /tmp runs out of space

### ISSUE THREAD

**Issue by konomikitten** [ib/xarchiver#100]
I have a `tmpfs` mount for `/tmp`

`tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime,size=1048576k`.

When xarchiver tries to extract a very large archive, in this case 500gb+ it errors out after `/tmp` runs out of space and leaves its temporary file behind.

`/tmp/xa-5DW6L0/xa-tmp.decompressed`

xarchiver should handle these issues better and not leave behind temporary files I need to go clean up.

**Comment by ib** [comment]
Why don't you just quit xarchiver? It'll clean up by itself.

**Comment by konomikitten** [comment]
I'm going to close this issue because I believe xarchiver ran out of memory and I can't seem to reproduce the bug now. I'll reopen it if the error happens again but I somehow doubt it will.
