### ISSUE TITLE
File in sub-folder inside RAR displayed with leading space when file size is big

### ISSUE THREAD

**Issue by Ski-lleR** [ib/xarchiver#101]
Hi,

That something i took me a while to understand, first i was thinking of badly formed RAR archive, but actually it is not.

Assuming you have this folder on drive :
Test
Test/big_file (1013577544 bytes)
Test/small_file (6 bytes)

So you rar it :
rar a "test_archive.rar" Test

If you open "test_archive.rar" in xarchiver, you get this :
![Capture d’écran_2020-08-02_10-37-27](https://user-images.githubusercontent.com/183827/89119156-41b3fe80-d4ac-11ea-85bb-257dc06dd8f6.png)

But there is no " Test" (with leading space) folder as you see on the command used for compression.

I'm not sure, but if think that come for rar program (well if it's used for listing, that i don't know), because if you type :
rar l "test_archive.rar"

This is what you got :
![Capture d’écran_2020-08-02_10-41-02](https://user-images.githubusercontent.com/183827/89119221-c1da6400-d4ac-11ea-939c-fb8245d9c695.png)

I say i'm not sure cause the filename "Test/big_file" is not aligned because actual file size in column "Size" is out of column, but in the end all column content are displayed 2 space separated correctly.

**Comment by ib** [comment]
Fixed.

**Comment by ib** [comment]
Fixed.

**Comment by ib** [comment]
Fixed.

**Comment by ib** [comment]
Fixed.

**Comment by ib** [comment]
Fixed.

**Comment by ib** [comment]
Fixed.
