### ISSUE TITLE
UnRAR 6.x.x support

### ISSUE THREAD

**Issue by mozurin** [ib/xarchiver#103]
After I upgraded UnRAR from 5.9.4 to 6.0.2, xarchiver cannot open rar archive files correctly. 
Executed command and its results of both versions shown in "Action -> Cmd-line output" seem to be identical, but with 6.0.2, xarchiver stucks at "Opening archive, please wait..." message and no files displayed.

As far as I can see, `xa_rar_check_version()` that only checks wether first character of UnRAR version is '5' or not, is causing xarchiver to recognize 6.0.2 as older one. So it looks like wrong output parser is waiting at stdout, expecting different format.

Experimentally, roughly modifying `*(strchr(id, ' ') + 1) == '5' ?` to `*(strchr(id, ' ') + 1) >= '5' ?` fixes the issue on my laptop, but I don't know all UnRAR functionalities xarchiver using are compatible between 5 and 6. Could you add UnRAR 6.x.x support to xarchiver?

**Comment by ib** [comment]
Thanks for the information, I will support version 6 asap.

**Comment by ib** [comment]
Fixed.
