### ISSUE TITLE
URL linked in Help > About for "Website" leads to 404 (?)

### ISSUE THREAD

**Issue by hobbsy** [ib/xarchiver#107]
Hi - I could be wrong but in the Help > About section for xarchiver 0.5.4.14 (as seen in the default vanilla install on Raspberry Pi OS for example)

it links to "Website"

with the URL:

https://wiki.github.com/ib/xarchiver

which seems to be a 404

`
Whoa there!

You have sent an invalid request.

Please do not send this request again.
Contact Support — GitHub Status — @githubstatus
`

**Comment by ib** [comment]
Thanks for reporting, GitHub changed the URL.
