### ISSUE TITLE
xarchiver crashes with message An error occurred while accessing the archive

### ISSUE THREAD

**Issue by RusselKane** [ib/xarchiver#108]
If I try to compress folder with long file names of the kind `data_pack_setup_something_test_cdab_410_215.501.932.1647_march_beta_-_update_(10471).pcb` using right click compress, at the end of compression procedure I get message
_**An error occurred while accessing the archive**_,
if the compression format is zip the compressed archive file  vanish,
if the format is tar the archive seems working, 
if the format is lrzip no archive is created at all.

**Comment by ib** [comment]
Which program (file manager?) do you use to right-click compress?

**Comment by RusselKane** [comment]
> Which program (file manager?) do you use to right-click compress?

The default Raspberry Pi OS filemanager

**Comment by ib** [comment]
> The default Raspberry Pi OS filemanager

Which is named what?
There should be a Help/Info menu item revealing name and version.

**Comment by ib** [comment]
Closed for lack of response.

**Comment by RusselKane** [comment]
@ib The filemanager is PacmanFM the default filemanager of LXDE desktop environment
