### ISSUE TITLE
xz archive creation creates an archive with another archive inside it and a single file

### ISSUE THREAD

**Issue by RusselKane** [ib/xarchiver#110]
If I compress a folder with xarchiver selecting xz format, xarchiver creates  an xz archive that contains a single archive file inside it, if I try to extract it, this file is in turn another compressed archive of an unspecified format that if I try to open as zip file it shows only a file despite the size is  as large as an archive that should contain all the folder files, in fact, it is the same size of the one created selecting tar.xz that shows all files as supposed

**Comment by ib** [comment]
Please explain exactly (step by step) how you compress. On the command line, with xarchiver itself or with a file manager?

**Comment by RusselKane** [comment]
> Please explain exactly (step by step) how you compress. On the command line, with xarchiver itself or with a file manager?

Right click from the default Raspberry Pi OS filemanager,
Choose _xz_ Archive type.

If rather than xz I choose tar.xz the archive is compressed correctly

**Comment by ib** [comment]
xz (like lrzip in #108) is a compressor that can only compress single files - not directories.
