### ISSUE TITLE
SIGSEGV if permission denied on folder 

### ISSUE THREAD

**Issue by kittennbfive** [ib/xarchiver#114]
version: current master (downloaded on Jan 18 2021)

If you try to compress a complete directory that contains some folder that you are not allowed to access Xarchiver crashes with SIGSEGV.

command line:
```
./xarchiver --compress=
```

file system structure:
```
xarchiver-master/test/folder1# ls -l
drw------- 2 root root 4096 Jan 18 07:07 folder2_private
```

result: crash because readdir() is called with a NULL-ptr

expected result: no crash

fix: attached

[patch1.diff.txt](https://github.com/ib/xarchiver/files/5828365/patch1.diff.txt)

**Comment by ib** [comment]
Fixed.
