### ISSUE TITLE
Fix "duplicate filenames on disk" for some command line

### ISSUE THREAD

**Issue by kittennbfive** [ib/xarchiver#115]
version: current master (downloaded on Jan 18 2021)

command line:

```
./xarchiver --compress= somefile.txt
(notice the space after the equal!)
```

result:
```
Command: /usr/bin/7z a -ms=off -mx=5 -bd -spd -y /<redacted>/xarchiver-master/test/t.7z '.' './myfile.txt' './xarchiver' './myfile.txt.7z' './file2.txt' 'myfile.txt'

ERROR:
Duplicate filename on disk:
myfile.txt
myfile.txt
```

reason: The space after the equal sign makes variable "opt_compress" contain nothing ("") and this creates some mess.

You may say that there should be no space after the equal sign and that the bug is in front of the computer, but i still think this is a valid bug as there is some weird behavior instead of a clear error message. In my opinion Xarchiver should only consider the entire directory if the argument is --compress=(nothing here at all) or at least print a better error message. If there is a file (or several) following the --compress argument, even with a space after the equal, Xarchiver should only add those files to the archive.

my patch: attached

[patch2.diff.txt](https://github.com/ib/xarchiver/files/5828384/patch2.diff.txt)

**Comment by ib** [comment]
I decided that there should be an error message.

The (long name) option must not be empty.

Thanks for reporting.
