### ISSUE TITLE
Compression task crashes with argument too long error

### ISSUE THREAD

**Issue by RusselKane** [ib/xarchiver#116]
If I try to compress a large folder with many files and subfolders few minutes after the start appears an error message complaining about a too long argument.

- The error appears regardless the compression format selected 
- I can compress it using the command line without problems
- Although the selected folder has many content it was only 1 selection, in a similar situation the archiver should generate a single target argument to indicate to compress selected folder with all its content, from the error message seems xarchiver bogusly tries something different exceeding the argument length

Filemanager PacmanFM 1.3.1 (the default LXDE filemanager)
OS Debian ARM64

**Comment by ib** [comment]
See #43.
