### ISSUE TITLE
Extraction of RAR archives freezes 

### ISSUE THREAD

**Issue by RusselKane** [ib/xarchiver#117]
I have several RAR5 archives if I try to extract them using right click (even if I try one at a time), the extraction freezes with very high CPU usage of xarchiver process while the unrar process (that actually should handle the extraction) CPU use remain at  0%,.
Not all files are extracted.

If I try to use unrar directly from command line, it extract them fine without any problem

Filemanager PacmanFM 1.3.1 (the default LXDE filemanager)
OS Debian ARM64

**Comment by ib** [comment]
What does `xarchiver -i` (on the command line) say?

Does the extraction finish? If so, start xarchiver, select Action/Preferences and check "Store archiver output". Extract. Action/Cmd-line output will give you more detailed error information. Click "Show command" and post output.

**Comment by RusselKane** [comment]
The output of `xarchiver -i` is the following
```
xarchiver 0.5.4 ©  2005-2014 Giuseppe Torelli
xarchiver 0.5.4.14 Ingo Brückl
7zip:
  /usr/bin/lsar
  /usr/bin/unar
arj:
  /usr/bin/lsar
  /usr/bin/unar
bzip2:
  /bin/bzip2
compress:
  /bin/uncompress
cpio:
  /bin/cpio
deb:
  /usr/bin/ar
gzip:
  /bin/gzip
lha:
  /usr/bin/lsar
  /usr/bin/unar
lrzip:
  /usr/bin/lrzip
lzma:
  /usr/bin/lzma
rar, rar5:
  /usr/bin/unrar
rpm:
  /bin/cpio
tar:
  /bin/tar
xz:
  /usr/bin/xz
zip, apk, cbz, epub, jar, oxt, xpi:
  /usr/bin/unzip
  /usr/bin/zip
```

**Comment by ib** [comment]
> xarchiver 0.5.4.14

This is quite old.

Does the RAR archive have a password?

Try current version 0.5.4.16 of xarchiver.

(And please answer my questions completely if you want support).

**Comment by ib** [comment]
Closed for lack of response.

**Comment by vitacell** [comment]
It happens always and only with LXDE desktop. Killing "xarchiver" from Htop, solves the freeze. I think, it's not xarchiver's problem.

**Comment by etiennemlb** [comment]
Xarchiver reject opening a .cbr archive which is simply a RAR archive with a different extension. .cbr files play a similar role to the .cbz files, these are commonly found for EBooks AFAIK.

**Comment by ib** [comment]
@etiennemlb

Please open an issue to request missing support for cbr comic book files. Implementation is easy as you can already open them from within xarchiver.

**Comment by ib** [comment]
@vitacell

Could you please elaborate?
