### ISSUE TITLE
Unar support

### ISSUE THREAD

**Issue by zifxify** [ib/xarchiver#12]
Xarchiver currently doesn't work with unar to unpack rar and other file formats but instead uses the proprietary unrar.
Unar 1.10 does support RAR 5.0 archives.

**Comment by ib** [comment]
> Unar 1.10 does support RAR 5.0 archives.

Yes, but this support is still buggy. Please keep that in mind.

Support for unar has been added.

**Comment by mckaygerhard** [comment]
i tested the current support for unar and are VERY BUGGY .. however.. i can see that xarchiver uses unrar as alternatives. seems falback to 7zip-rar ... i'll open a new bug report and let this commet here as a note important

**Comment by ib** [comment]
There is (within the limits of the unar capabilities) full unar support.
