### ISSUE TITLE
Cannot open password encrypted RAR archives

### ISSUE THREAD

**Issue by AngryPhantom** [ib/xarchiver#120]
Encrypted RAR archives cannot be opened via Xarchiver

I'm on Debian Stable with MATE DE (as well as Void Linux with XFCE).

#### Steps to reproduce the behaviour
Install any RAR for Linux version **after** 5.7.1. For example, the latest (as of now): [6.0](https://www.rarlab.com/rar/rarlinux-x64-6.0.0.tar.gz). You can simply unpack the files somewhere in your /usr/local/bin, usr/local/lib and /etc (there is a makefile with the paths inside every RAR release archive).

#### The problem
Cannot open password encrypted RAR archives and get the following [error](http://0x0.st/-8zs.png).

Everything was fine with RAR versions before (and including) 5.7.1 (so I reverted back to using [5.7.1](https://www.rarlab.com/rar/rarlinux-x64-5.7.1.tar.gz)). That's how [it should look](http://0x0.st/-8zi.png) when you open an archive. It should prompt for a password.

I also started Xarchiver from the console to see if there are any errors, but there weren't.

When I extract such archives in console using the unrar command everything is OK, so I guess it's not a RAR bug.

Here is a test archive file with a (password: **1**) for you to try: https://gofile.io/d/nMUmle
The same is here (if the above link doesn't work): https://file.io/UdwPAvvcUGLI

Could someone reproduce it please?

Thank you in advance,
Alex

**Comment by ib** [comment]
> Cannot open password encrypted RAR archives and get the following error.

This error indicates that rar/unrar cannot be found. How/where did you install rar-6.0.0? What does `xarchiver -i` say on the console?

> Here is a test archive file with a (password: 1) for you to try

I can open the archive with rar/unrar 6.00 without problems.

**Comment by AngryPhantom** [comment]
> How/where did you install rar-6.0.0

Just downloaded the release from the official site and installed with 'make install'. It is installed in /usr/local/bin, usr/local/lib and /etc.

[xarchiver -i](https://pastebin.com/raw/i0F9reYs)

I mean, it's rather strange for me because it worked without problems before (and including) version 5.7.1.

Btw, it also stopped working for people using Engrampa archive manager from MATE DE. They could reproduce it and fixed the [issue](https://github.com/mate-desktop/engrampa/issues/374) recently.

If it works for you then I'm at a loss, really, since it doesn't work on different Linux distros.

**Comment by AngryPhantom** [comment]
The only difference with 'xarchiver -i' between versions 5.7.1 and 6.0 is a string:

```
rar, rar5:
/usr/local/bin/rar
```

and

```
rar:
/usr/local/bin/rar
```

**Comment by ib** [comment]
> xarchiver -i
> xarchiver 0.5.4.14

This version is too old. It does not support rar/unrar 6 (see issue #103).

You need at least xarchiver 0.5.4.16. The latest version 0.5.4.17 is recommended though.
