### ISSUE TITLE
Parallel (multi-threaded) compression/decompression is not supported

### ISSUE THREAD

**Issue by nikodll** [ib/xarchiver#121]
There are plenty of multi-threaded implementations for common archive types (lbzip2 / pbzp2 / pigz) that are _direct_ replacements for standard command line tools and libraries. Somehow, xarchiver still doesn't allow user to take advantage of multi-threading available on 99.99% user systems. Millions of user-hours are just wasted, waiting for slow archive processing.

**Comment by ib** [comment]
You should not use xarchiver if it wastes your time!

pigz, lbzip2, pbzip2 and plzip are supported since version 0.5.4.15, almost a year ago.

**Comment by nikodll** [comment]
Hi ib,

I'm using xarchiver v0.5.4.15-3 on Ubuntu 20.10 with both lbzip2 (v2.5-2) and pbzip2 (v1.1.13-1build1) packages installed. Would you mind to help me figure out why xarchiver still uses bzip2 (i.e. works single threaded)? It therefore works much slower when comparing to e.g. engrampa on the same system, which is somehow able automatically pick up and use lbzip2.
