### ISSUE TITLE
xarchiver 0.5.4.17 crash for open .zip 

### ISSUE THREAD

**Issue by uratom962** [ib/xarchiver#123]
On archlinux : 

Description:

Additional info:
* package version(s)
```
$ xarchiver -v
xarchiver 0.5.4.17

Maintained by Ingo Brückl.

Copyright (c) 2005-2014
Giuseppe Torelli - Colossus <colossus73@gmail.com>

Please report bugs to <https://github.com/ib/xarchiver/issues>.
```

* config and/or log files etc.
```

]$ uname -a
Linux zeni 5.11.0-zen1-1-zen-anbox #1 ZEN SMP PREEMPT Wed, 10 Mar 2021 03:35:58 +0000 x86_64 GNU/Linux
```

* link to upstream bug report, if any

Steps to reproduce:

when I open this software gui and I want to open .zip I have this :

```
$ xarchiver
Segmentation fault (core dumped)
```

I can unzip in command line.

**Comment by ib** [comment]
I need more information.

What is your unzipper (`xarchiver -i`)? What does your unzip command say with `--version`?

Can you provide a sample zip that crashes?

**Comment by uratom962** [comment]
`$ xarchiver -i
xarchiver 0.5.4 ©  2005-2014 Giuseppe Torelli
xarchiver 0.5.4.17 Ingo Brückl
7zip:
  /usr/bin/7z
ar, deb:
  /usr/bin/ar
arj:
  /usr/bin/7z -tarj
bzip2:
  /usr/bin/bzip2
compress:
  /usr/bin/uncompress
cpio:
  /usr/bin/cpio
gzip:
  /usr/bin/gzip
lha:
  /usr/bin/7z -tlzh
lz4:
  /usr/bin/lz4
lzma:
  /usr/bin/lzma
rar, rar5:
  /usr/bin/7z -trar
  /usr/bin/7z -trar5
rpm:
  /usr/bin/cpio
tar:
  /usr/bin/tar
xz:
  /usr/bin/xz
zip, apk, cbz, epub, jar, oxt, xpi:
  /usr/bin/7z -tzip
zstd:
  /usr/bin/zstd`

`]$ xarchiver --version
xarchiver 0.5.4.17 

Maintained by Ingo Brückl.

Copyright (c) 2005-2014
        Giuseppe Torelli - Colossus <colossus73@gmail.com>

Please report bugs to <https://github.com/ib/xarchiver/issues>.`

And all of my .zip (like music, or documents) ...

**Comment by ib** [comment]
```
zip, apk, cbz, epub, jar, oxt, xpi:
  /usr/bin/7z -tzip
```
Strange. There are no known problems with 7z.

What does `/usr/bin/7z | head -n 4` say?

**Comment by uratom962** [comment]
Hi ! thank you for help.

$ /usr/bin/7z | head -n 4

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs x64)

**Comment by ib** [comment]
7-Zip 17.04 is a fork of the official 7-Zip, but even with this version I have no problems. I can't reproduce the error and I can't explain why there is a segmentation fault.

Please attach a core dump here, maybe I can figure something out.

**Comment by uratom962** [comment]
How to attach core dump ?

**Comment by ib** [comment]
You wrote:

    when I open this software gui and I want to open .zip I have this :

    $ xarchiver
    Segmentation fault (core dumped)

So there should be a core dump, i.e. a file named `core`. Zip this file (probably not with xarchiver :smirk:) and attach it to a comment here.

**Comment by uratom962** [comment]
I can't do that I don't Know sorry

**Comment by ib** [comment]
I can't help then.

Open a terminal, `cd /tmp`, type `xarchiver` to call it and open a zip file. There should be a file named `core` in /tmp then. ` zip core.zip core` and attach core.zip to your next comment here.

**Comment by City-busz** [comment]
@uratom962: you can get a proper backtrace as described in [Arch Wiki](https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces). The `coredumpctl dump` command is also useful after the crash happened.

**Comment by ib** [comment]
Closed for lack of response.
