### ISSUE TITLE
Right Click Extract zstd compressed files

### ISSUE THREAD

**Issue by mehargags** [ib/xarchiver#124]
I'm using XArchiver on Debian 10 + LXDE + PCManFM, I'd like to be able to 'right click' extract my .zst files like I can with my .tar and .gz files. What would be the settings / config edits to do so that .zst files are recongnised properly by XArchiver.  

When I open (by dbl clicking) a zstd compressed archives, the tar.zst files open but single files like .sql files do not show up in the archiver's explorer.

Any tips ?

**Comment by ib** [comment]
What does `xarchiver -i` say?

.zst files are supported since 0.5.4.14, tar.zst files since 0.5.4.15.

**Comment by ib** [comment]
Closed for lack of response.
