### ISSUE TITLE
How to know how long it will take to compress I file?

### ISSUE THREAD

**Issue by txirrindulari** [ib/xarchiver#125]
Hi,
I just see at lower part of the window "adding file, please wait..",
Is there any way to know the % done so far or an estimation of how long will it take?

thank you

**Comment by ib** [comment]
Unfortunately, no. 

For this, all programs called in the background would have to report their progress, which they unfortunately don't do.

Only Multi-Extract provides a percentage of progress, but this only refers to the number of archives, not to their extraction time.

**Comment by ib** [comment]
Closed for lack of response.
