### ISSUE TITLE
Nothing happens with RAR4-files, RAR5 are not supported

### ISSUE THREAD

**Issue by addeps3** [ib/xarchiver#126]
I dont know what happened but xarchiver is broken for me. I got it from fedora's repo's

ON xfce, if opening with context menu, and clicking extract on a RAR5 file, a window prompt states "Sorry this archive is not supported, The proper archiver is not installed" 

`echo $PATH
/home/TomHanks/.local/bin:/home/TomHanks/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
`
`which unrar
/usr/bin/unrar
`

`unrar | grep "^UNRAR "
UNRAR 6.01 freeware      Copyright (c) 1993-2021 Alexander Roshal
`
If doing the same with a RAR4 file, result is indefinite "Opening archive, please wait..." 

`unrar -x anything.rar ` works flawlessly

Oh, current version: xarchiver 0.5.4.14

**Comment by addeps3** [comment]
`unar -v
v1.10.1
`

**Comment by ib** [comment]
Does the RAR archive have a password?

What does happen when you start xarchiver and open the file from there?

Does any extraction finish? If so, start xarchiver, select Action/Preferences and check "Store archiver output". Extract. Action/Cmd-line output will give you more detailed error information. Click "Show command" and post output.

> Oh, current version: xarchiver 0.5.4.14

This is quite old. Current version is 0.5.4.17.

**Comment by addeps3** [comment]
> > Oh, current version: xarchiver 0.5.4.14
> 
> This is quite old. Current version is 0.5.4.17.

Thats not unexpected, since fedora repo's arent bleeding edge whatsoever. 
I'll try building and installing latest xarchiver soon. 

Oh, now I found the cmd-line output: 

`
Archive: /home/adam/Downloads/1425316445_Bobber Mix and fggio Wheel.rar
Details: RAR 4

 Attributes      Size    Packed Ratio    Date    Time   Checksum  Name
----------- ---------  -------- ----- ---------- -----  --------  ----
    ..A....   2395181   2252740  94%  2015-03-02 17:20  C4503DF0  Bobber Mix and fggio Wheel/bobber.wft
    ..A....    421966    413724  98%  2015-03-02 17:21  92C5C3DD  Bobber Mix and fggio Wheel/bobber.wtd
    ..A....    480401    463022  96%  2015-03-02 17:20  0B6FB898  Bobber Mix and fggio Wheel/faggio.wft
    ..A....     80647     80009  99%  2015-03-02 17:21  1A98D568  Bobber Mix and fggio Wheel/faggio.wtd
    ...D...         0         0   0%  2015-03-02 17:33  00000000  Bobber Mix and fggio Wheel
----------- ---------  -------- ----- ---------- -----  --------  ----
              3378195   3209495  95%                              5

`
I can not get a output on a RAR5 file since prompt pops up, and Cmd-line output is greyed out. Store Archiver output is enabled.

**Comment by addeps3** [comment]
Everything works with master-branch. 

Thank you, and closing!

**Comment by addeps3** [comment]
Im just reporting that at the time we discussed this issue: executing xarchiver from CLI, after running sudo make install reported that xarchiver could not be found in /usr/lib 
I have resolved this myself by just cp-ing the binary to the system-folder, but in case this was oversight, I just thought you'd want to know. 

Regards/ A.J

**Comment by ib** [comment]
The binary should be installed in /usr/local/bin unless a --prefix is given.

From where did you copy it?

**Comment by ib** [comment]
> I understand, I assumed /usr/bin was correct.

`./configure --prefix=/usr` should do that and report `xarchiver 0.5.4.17 configured for /usr using GTK+ ...`

**Comment by addeps3** [comment]
I had just had a look in /usr/local/bin and the binary is there. I dont know why, but after running sudo make install, I couldnt start xarchiver from the terminal. 
Now it works, but right clicking, and "Extract here" doesnt work, I get "Failed to extract files, No suitable archive manager found"

**Comment by ib** [comment]
Thunar, I suppose?

It looks for the mime type in the desktop files. Is xarchiver.desktop installed? Did you update the desktop database?

BTW, this kind of support is beyond xarchiver issues.

**Comment by addeps3** [comment]
Yes, thunar. 

Well, nevermind then. Thanks for the info.
