### ISSUE TITLE
Segfault if archive contains apostrophe in file name

### ISSUE THREAD

**Issue by Ammako** [ib/xarchiver#130]
What the title says. Doesn't show much more than just `Segmentation fault (core dumped)` in terminal, but I'm guessing it just doesn't take into account that file names can contain apostrophes and it might be prematurely terminating strings somewhere that it shouldn't be...

**Comment by ib** [comment]
> I'm guessing it just doesn't take into account that file names can contain apostrophes

Actually it does - not only apostrophes, but all critical characters.

Please provide more information. What exactly did you do? Which version does xarchiver have? Of what type is the archive? Could you post the archive?

**Comment by Ammako** [comment]
0.5.4.17, but also reproduced on latest commit that I built.

.zip archive, literally any archive does it. zipping any random file I have, I can extract the archive just fine but it fails if I add a ' to the file name.

Arch Linux, Xfce, 4.16, en_CA.UTF-8 locale, I wish I could provide more information but it really doesn't give me much to work with when it crashes. Can I build or run with additional debug output enabled? Would that even help?

**Comment by Ammako** [comment]
.7z works, .rar works, .zip segfaults.

**Comment by ib** [comment]
> I wish I could provide more information

Do you open from the command line (post command please) or do you start xarchiver and open then?

> .zip archive

Which program handles zip (`xarchiver -i`) and what version is that program?

> zipping any random file I have, it fails if I add a ' to the file name.

Please post such a file here.

> Can I build or run with additional debug output enabled?

Sure: `--enable-debug=full`.

> Would that even help?

Running with `gdb` should tell what happens.

**Comment by ib** [comment]
> .7z works, .rar works, .zip segfaults

So, what handles your .zip files? Maybe a script?

**Comment by Ammako** [comment]
> Do you open from the command line (post command please) or do you start xarchiver and open then?

Open by double-click from file manager (Thunar), but the same crash happens if I use command line to open Xarchiver (just `xarchiver`) and/or drop the .zip into the Xarchiver window.

> Which program handles zip (xarchiver -i) and what version is that program?

```
zip, apk, cbz, epub, jar, oxt, xpi:
  /usr/bin/7z -tzip
```

```
7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_CA.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)
```

Note I'm able to read and extract the archive just fine if I skip the middleman and run `7z -tzip l arch\'ive.zip` or `7z -tzip x arch\'ive.zip`directly, but trying to open the same archive in Xarchiver fails.

> Please post such a file here.

Works: [chain.zip](https://github.com/ib/xarchiver/files/6836126/chain.zip)
Exact same file, renamed: [cha'in.zip](https://github.com/ib/xarchiver/files/6836128/cha.in.zip)

(looks like GitHub replaced that ' with a ., just make sure to rename it after the fact but honestly you can just rename the first archive too and you don't need the second one.)

> Sure: --enable-debug=full.

```
free(): invalid pointer
Aborted (core dumped)
```

> Running with `gdb` should tell what happens.

```
free(): invalid pointer
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "xarchiver" received signal SIGABRT, Aborted.
0x00007ffff6f07d22 in raise () from /usr/lib/libc.so.6
```

**Comment by ib** [comment]
Okay, I can reproduce with `7z -tzip`.

**Comment by ib** [comment]
Should be fixed now.
