### ISSUE TITLE
busybox cpio support

### ISSUE THREAD

**Issue by HGpunktT** [ib/xarchiver#133]
xarchiver does not work with busybox cpio, because the layout of output from `cpio -tv -F _archive_` is different from that of GNU cpio.
Both are located in [/usr]/bin/cpio but can be distinguished easily:
With GNU cpio this is a regular file, whereas with busybox cpio this is a symbolic link to /bin/busybox.
Would be nice to have xarchiver working with busybox cpio also.

**Comment by ib** [comment]
I am not sure whether to support such programs that have the same name but are not compatible.

This is more likely a busybox issue.

**Comment by ib** [comment]
There will be no support for programs that have the same name but are not compatible.
