### ISSUE TITLE
Unpack without directory tree

### ISSUE THREAD

**Issue by DmitruMoth** [ib/xarchiver#137]
Hello, can you add option for unpack files / directories without recreate directory tree?
How it works now: pick file, move it to a file manager, get full directory tree and your file.
What i want: pick file, move it to a file manager, get single file without directory tree.

**Comment by ib** [comment]
Which file manager?

**Comment by DmitruMoth** [comment]
Thunar

**Comment by ib** [comment]
Extract once from within `xarchiver` unselecting `Extract files with full path`.
