### ISSUE TITLE
"Unknown compression type!" opening .rpm file with zstd payload compression

### ISSUE THREAD

**Issue by bretth25** [ib/xarchiver#138]
RPMs switched to zstd compression in Mar 2020 (https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression).

The attached patch file appears to resolve the issue
[rpm_with_zstd_payload.patch.txt](https://github.com/ib/xarchiver/files/7754515/rpm_with_zstd_payload.patch.txt)
. 

This patch builds and tests ok.

Thanks.

**Comment by ib** [comment]
Thanks a lot, patch applied.
