### ISSUE TITLE
cannot open password-protected archives containing spaces

### ISSUE THREAD

**Issue by PaulchenPlump** [ib/xarchiver#141]
The file [PW 1234.zip](https://github.com/ib/xarchiver/files/8244108/PW.1234.zip) cannot be unpacked as long as the space is still included. It does not matter if 7z or unzip is used. Renaming it to e.g. "PW_1234.zip" is sufficient for it to work.

**Comment by ib** [comment]
Which xarchiver version are you using?

**Comment by PaulchenPlump** [comment]
Sorry - I use version 0.5.4.17 under Debian 11

**Comment by ib** [comment]
What does **Cmd-line output** including **Show command** say (after enabling **Store archiver output** in the preferences)?

**Comment by PaulchenPlump** [comment]
`Kommando: /usr/bin/7z -tzip e -aos -bd -spd -y /path/to/zipfile/PW\ 1234.zip 'testfile.txt' -o/target/path


7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Common KVM processor (F61),ASM)

Scanning the drive for archives:
1 file, 229 bytes (1 KiB)

Extracting archive: /path/to/zipfile/PW 1234.zip
--
Path = /path/to/zipfile/PW 1234.zip
Type = zip
Physical Size = 229


ERROR: Wrong password : testfile.txt
Enter password (will not be echoed):
Sub items Errors: 1

Archives with Errors: 1

Sub items Errors: 1`

Already in the listing of files in xarchiver no "key icon" for password protected is displayed!

**Comment by ib** [comment]
The fix for #130 also fixes this issue. So you either have to compile xarchiver by yourself or you have to wait for the next release which should come soon.
