### ISSUE TITLE
Possible Bug: Busybox compatibility for *.gz

### ISSUE THREAD

**Issue by Saijin-Naib** [ib/xarchiver#144]
![image](https://user-images.githubusercontent.com/19295950/164946903-e1e7d4ab-f848-410c-9bed-66d3e0307434.png)

```
Command: /bin/gzip -l /home/USERNAME/aports/clamtk/src/clamtk-6.14/clamtk.1.gz
```

```
/bin/gzip: unrecognized option: l
BusyBox v1.35.0 (2022-04-20 13:37:22 UTC) multi-call binary.

Usage: gzip [-cfkdt123456789] [FILE]...

Compress FILEs (or stdin)

	-1..9	Compression level
	-d	Decompress
	-c	Write to stdout
	-f	Force
	-k	Keep input files
	-t	Test integrity
```

**Comment by ib** [comment]
I am not sure whether to support such programs that have the same name but are not compatible.

This is more likely a busybox issue.

**Comment by Saijin-Naib** [comment]
I've filed an issue upstream with Busybox referencing this and the GNU GZip documentation for the -l flag.

**Comment by ib** [comment]
There will be no support for programs that have the same name but are not compatible.
