### ISSUE TITLE
Drag and drop on a selection will only extract the first file from the list

### ISSUE THREAD

**Issue by cmvizitiu** [ib/xarchiver#147]
Not entirely sure whether this is bug report or a feature request but anyway: 

0.5.4.17 running on FC35; Thunar 4.16.11 or Nemo 5.2.3. 

Have either Thunar or Nemo with a panel opened in the folder where I want the files to be extracted. 

Open an archive and click your way to the list of files inside the archive then select a bunch of files from the archive and drag them to the Thunar/Nemo window. 

Although I've selected multiple files, only the first file in the selection gets extracted. 

OTOH if I right click on the selected list of files and chose "Extract" then all files are extracted. Trouble is, the destination folder might be deep in a folder hierarchy so choosing it from the file selector becomes a nuisance, most of the times it's way easier to simply drag and drop.

**Comment by ib** [comment]
See #72 and use 0.5.4.18.
