### ISSUE TITLE
Cannot open files or directories

### ISSUE THREAD

**Issue by aianson** [ib/xarchiver#148]
Using 0.5.4.18 I can't open files or directories with the mouse.

I don't know if that is a bug or a build/config issue.

**Comment by ib** [comment]
A bit more (detailed) information on what exactly you are trying to do would be helpful.

**Comment by aianson** [comment]
On Mon, 30 May 2022 12:23:58 -0700
ib ***@***.***> wrote:

> A bit more (detailed) information on what exactly you are trying to do would be helpful.

Using xarchiver 0.5.4.17 I could click with the mouse to open a directory. I can't do that with 0.5.4.18.

The same with opening a text file within an archive. I could click a text file and open it with my selected text editor. I can't do that with 0.5.4.18.

I can select a directory from the tree view on the left side of xarchiver's window to view a directory and I can choose "open with" to open a text or other file.

I just can't use the mouse to open a file or directory anymore.

**Comment by ib** [comment]
More questions:

* Did you compile it yourself?
* Do you use a distribution? (If yes, which one?)
* Can you select a file / directory with the left mouse button?
* Does the popup menu appear when clicking with the right mouse button?

**Comment by aianson** [comment]
On Tue, 31 May 2022 09:40:59 -0700
ib ***@***.***> wrote:

> More questions:
> 
> * Did you compile it yourself?

No, I compiled 0.5.4.17 and copied the binary to /usr/bin just to see the difference.

> * Do you use a distribution? (If yes, which one?)

Yes, I have an up to date archlinux setup.

> * Can you select a file / directory with the left mouse button?

Yes, I can select different files/directories with the left button but double clicking doesn't open them.
 
> * Does the popup menu appear when clicking with the right mouse button?

Yes, I can right click a file with the right mouse button and select "open with" or "view" to open a text file. It just seems that double clicking doesn't work for me in 0.5.4.18. I'm not sure why.

**Comment by ib** [comment]
Okay, now I understand.

Do you have a 3-button mouse? The middle button should trigger a double click.

The missing double-click with the left mouse button is a regression.

**Comment by aianson** [comment]
On Fri, 03 Jun 2022 02:52:03 -0700
ib ***@***.***> wrote:

> Okay, now I understand.
> 
> Do you have a 3-button mouse? The middle button should trigger a double click.

Yes, but I never tried the middle button. It does trigger a double click.

> The missing double-click with the left mouse button is a regression.

Thanks for looking into this.

**Comment by ib** [comment]
Fixed.
