### ISSUE TITLE
Support to extract multiple files via drag and drop

### ISSUE THREAD

**Issue by surkamp** [ib/xarchiver#149]
I would like to suggest an enhancement by adding support for multiple files extraction via drag and drop.

Reproduce:

- Open an archive in xarchiver
- Select multiple files by shift clicking the archive's content
- Drag the files from xarchiver to your favourite file manager (I am using thunar on XFCE 4.16)

Current behavior: Only the file being dragged keeps selected and is extracted

Suggested behavior: Drag and extract all selected files

**Comment by ib** [comment]
Already fixed in 0.5.4.18.
