### ISSUE TITLE
wrong name for latest version

### ISSUE THREAD

**Issue by ousia** [ib/xarchiver#15]
@ib,

I’m afraid that both links to latest stable (either https://github.com/ib/xarchiver/archive/xarchiver-0.5.4.8.zip or https://github.com/ib/xarchiver/archive/xarchiver-0.5.4.8.tar.gz) download `xarchiver-xarchiver-0.5.4.8.zip` or `xarchiver-xarchiver-0.5.4.8.tar.gz`.

At least the second file contains a `xarchiver-xarchiver-0.5.4.8` directory.

Just in case it helps.

**Comment by ib** [comment]
Thank you very much for pointing this out.

I've corrected it by renaming all lightweight tags (which github creates my releases from).

So anyone having a local repository and wanting to be in sync is advised to:
```
git tag -d $(git tag -l xarchiver-0.5.[2-4].[1-8])
git fetch --tags
```
