### ISSUE TITLE
zip archiving doesn't work with folders

### ISSUE THREAD

**Issue by Ingsantirodriguez** [ib/xarchiver#150]
When trying to compress a folder if the format selected for the archive is .zip, the folder is compressed but as an empty folder. The same happens if I try to compress multiple files and a folder, all files are compressed correctly but with the folder I have the same issue

**Comment by ib** [comment]
Did you select _Options_ → _Include subdirectories_?

**Comment by Ingsantirodriguez** [comment]
I was compressing it from pcmanfm's compress option when right clicking. That option does not appear, I guess that was the issue.
