### ISSUE TITLE
extracting packages with a ./ root directory dont honor "ensure containing directory"

### ISSUE THREAD

**Issue by fbrau** [ib/xarchiver#159]
For example this archive
[https://github.com/andrewchambers/bupstash/releases/download/v0.11.1/bupstash-v0.11.1-man.tar.gz](https://github.com/andrewchambers/bupstash/releases/download/v0.11.1/bupstash-v0.11.1-man.tar.gz)

<pre>
./
./bupstash.1
./bupstash-authors.7
./bupstash-diff.1
./bupstash-exec-with-locks.1
./bupstash-gc.1
./bupstash-get.1
...
</pre>

I would expect this to be extracted to a containing bupstash-v0.11.1-man/ directory, but
they are expanded in the same destiny directory instead

**Comment by ib** [comment]
Did you select "Ensure a containing directory"?

What version are you using? Which distribution?

**Comment by ib** [comment]
First of all you have to use xarchiver 0.5.4.19. Without sidebar select "Ensure a containing directory", "All Files", "Without parent path".

**Comment by fbrau** [comment]
It works!! I was so used to the "with full path" option that I forgot to consider the other one. Thanks
