### ISSUE TITLE
allow recompression when compressed file is edited

### ISSUE THREAD

**Issue by ousia** [ib/xarchiver#16]
@ib, many compressors have this interesting feature (and I miss it in xarchiver):

Imagine that you have a compressed file with text files inside. You double-click on one of them. You modify the text. After you save the results in the temporary directory, xarchiver could ask whether you want to update the file.

It is an extremely useful feature.

Many thanks for your work.

**Comment by mirh** [comment]
Feature present for example in 7-zip for windows.

**Comment by ib** [comment]
It took some time, but I hope it was worth waiting for.

Finally realized.

**Comment by ousia** [comment]
Many thanks for the new feature, @ib.

**Comment by ousia** [comment]
I have just tested with current master (plus patch from https://github.com/ib/xarchiver/issues/143#issuecomment-1108769918) and I’m afraid I cannot make it work.

Open https://github.com/ib/xarchiver/files/8546204/book-epub.zip, edit `mimetype`, save it and xarchiver doesn’t prompt about file recompression.

What am I missing here?

**Comment by ib** [comment]
What prompt are you expecting? `mimetype` is always uncompressed and other files use default compression. (Did you choose `Replace`? Please see the [documentation](https://github.com/ib/xarchiver/commit/f1fec9cb3bad7cdc5fd43bf07a38957c2faaa9a6).)

**Comment by ib** [comment]
Should be more straightforward now.
