### ISSUE TITLE
clicking on a directory doesnt work 

### ISSUE THREAD

**Issue by fbrau** [ib/xarchiver#160]
The only way to access a subdirectory is by clicking on the archive tree. If you dont use that panel, the is only possible way is by pressing ENTER on such directory. Click doesnt work.

**Comment by ib** [comment]
I don't understand, could you please explain more detailed? Maybe you are looking for a double-click?

**Comment by fbrau** [comment]
yes. A double click. 
![Captura_2022-09-07_23-10-38](https://user-images.githubusercontent.com/8375315/189011667-ffc16110-0ca2-467f-adb3-a7cb39c7a965.png)

I want to double click to access to that "options" subdirectory (for example), but it doesnt work. I can press ENTER or enable the tree sidebar to change directories from there, but I dont like the sidebar... But anyways, the double click functionality is not there.

**Comment by ib** [comment]
xarchiver 0.5.4.18 is deprecated, please use 0.5.4.19.

**Comment by fbrau** [comment]
It works!!
