### ISSUE TITLE
wrong filename within archive

### ISSUE THREAD

**Issue by fbrau** [ib/xarchiver#162]
https://github.com/viktomas/godu/releases/download/v1.3.1/godu_1.3.1_Linux_x86_64.tar.gz

package contents:
<pre>
-rw-r--r-- runner/docker  1084 2022-09-17 05:55 LICENSE.md
-rw-r--r-- runner/docker  2751 2022-09-17 05:55 README.md
-rwxr-xr-x runner/docker 2449408 2022-09-17 05:55 godu
</pre>

![Captura_2022-09-24_15-12-58](https://user-images.githubusercontent.com/8375315/192112692-440074f8-e98a-4419-a411-b20a35ca9d1f.png)

It its parsing the 'godu' file as '5'

**Comment by ib** [comment]
Congrats, you found the bug I'm currently already working on.

**Comment by ib** [comment]
Fixed in current master.
