### ISSUE TITLE
`--ensure-directory` doesn't extract `.rpm` archive if `pwd` contains a space

### ISSUE THREAD

**Issue by kuraga** [ib/xarchiver#165]
```
$ xarchiver --version
xarchiver 0.5.4.20 
```

Let's we have a space in current path:
```
$ pwd
/home/user/Рабочий стол
```
And an `.rpm` file:
```
$ xarchiver --ensure-directory file.rpm
```

![image](https://user-images.githubusercontent.com/1063219/213870985-e5dc74db-6e6b-4007-999d-c4f4e9633242.png)

Similar to #94 ?

/cc @ib

**Comment by ib** [comment]
This seems to be related to UTF-8.

**Comment by kuraga** [comment]
@ib , it does work in `/home/sasha/Загрузки`.

**Comment by ib** [comment]
Fixed.
