### ISSUE TITLE
[Question] Supported file formats page

### ISSUE THREAD

**Issue by Gersonzao** [ib/xarchiver#167]
Are the file formats described in [the doc](https://github.com/ib/xarchiver/blob/master/doc/html/ch01s01.html) the only formats supported by Xarchiver or are there any other formats that weren't listed? I would like to know if there's a list of supported file formats somewhere else.

**Comment by ib** [comment]
All formats currently supported are listed in the [doc](https://github.com/ib/xarchiver/blob/master/doc/html/ch01s01.html) as well as in the [man page](https://github.com/ib/xarchiver/blob/master/doc/xarchiver.1). You can find the corresponding MIME types in [here](https://github.com/ib/xarchiver/blob/master/xarchiver.desktop.in).
