### ISSUE TITLE
Freeze while "Open with" dialog is opening

### ISSUE THREAD

**Issue by kuraga** [ib/xarchiver#168]
1. There is a small zip archive.
2. Right click on a file inside.
3. Click `Open with`.
4. The dialog is opening...
5. Freeze. 100% CPU using

xarchiver 0.5.4.20, XFCE 4.18, Calculate Linux (Gentoo)

**Comment by ib** [comment]
I can't do anything without that file for testing.

**Comment by kuraga** [comment]
[test.zip](https://github.com/ib/xarchiver/files/10737220/test.zip)

**Comment by ib** [comment]
Nothing unusual about this archive.

Does **every** archive freeze at `Open with`?

**Comment by kuraga** [comment]
Yes. Will I `gdb`, yeah?
