### ISSUE TITLE
left-side tree pane should show 'root'

### ISSUE THREAD

**Issue by mappu** [ib/xarchiver#17]
Hi,

Sometimes i do click through subdirectories in xarchiver and get confused about missing files.
I click through every directory in the tree view, and, my files are missing!

Of course... it's not possible to click "root" or "top" in the tree view to get a top-level directory...

Regards
mappu

**Comment by ib** [comment]
Which xarchiver version are you using?

Which archive type(s) are you referring to where files are missing?

What about the root button in the toolbar?

**Comment by mappu** [comment]
Sorry for unclear.

Files are not truely missing, the root button in the toolbar does really work.
But, i mistakenly thought that the tree view should be sufficient to reach any folder. The tree view is not sufficient to reach the root folder.
It would be more clear to me if the root folder was accessible via the tree view.

I have xarchiver 0.5.4 from debian stretch. Same behavior with all archive types (tar.xz, zip, 7z, ...)

**Comment by ib** [comment]
0.5.4 is a very old version known to be buggy and not supported here. Please use the latest [release](https://github.com/ib/xarchiver/releases).

**Comment by mappu** [comment]
Same in 0.5.4.8.

I guess it's to do with `archive_dir_model`. The `archive->root_entry` passed to `xa_browse_dir_sidebar` in `archive.c`, the recursion does start one level higher than i wanted.
But i don't know GTK any further.

**Comment by ib** [comment]
I've thought about it and have come to the decision that a dummy root or top entry isn't a good idea. It might confuse and do more harm than good.

There is the root button for root access, and there are two indicators for what you are listing (if anything) - namely a selected tree view item and the archive location bar entry.

Such a thing like a root or top entry will only exist if everything in the archive itself is inside a (top) directory.
