### ISSUE TITLE
Improve keyboard handling

### ISSUE THREAD

**Issue by W4RH4WK** [ib/xarchiver#171]
I just noticed two keyboard related issues with xarchiver:

1. Keybindings for the back / up / forward actions are missing. My suggestion would be Alt+left for back, Alt+up for up, Alt+right for forward. These bindings correspond to Windows Explorer's bindings.

2. Tree nodes in the side bar cannot be closed via keyboard. Even further, tree nodes are automatically expanded when selecting them with the up/down keys. This makes it very tedious to navigate to a node at the same depth, when the tree is large (wide and deep). I'd suggest not opening the nodes when navigating with the up/down keys; left closes a node, right (or space, or enter) opens a node.

**Comment by richo67** [comment]
This would be great. I am looking long time for tool to handle archives with keyboard only

**Comment by ib** [comment]
- Automatic node expansion can now be disabled in the preferences.

- Tree nodes in the sidebar could already be opened / closed with the plus / minus keys. I've enabled the right / left cursor keys for this as well.

- Keybindings for the back / up / forward / root actions have been added.
