### ISSUE TITLE
folder with dot in name not shown

### ISSUE THREAD

**Issue by swestlake** [ib/xarchiver#173]
when there is a folder with a dot in it, xarchiver does not display it, however xarchiver extracts the archive successfully.

xarchiver 0.5.4.20

**Comment by ib** [comment]
I can't reproduce. Could you give an example?

**Comment by swestlake** [comment]
you can close this bugreport -- next time I will specify much more detail. I forget what archive format it was and what exact directory name was used but the issue was very replicable as I recall. 

thanks
