### ISSUE TITLE
Extract multiple files on XFCE with Thunar

### ISSUE THREAD

**Issue by extremelyonline** [ib/xarchiver#178]
Hello,

Currently, on XFCE's thunar, when selecting several archive files, then right clicking on "Extract here", only the first archive is extracted.

This bug was reported 10 years ago, but the behavior persists on Debian 12. (Not sure if this should be solved on Thunar's side or xarchiver's side, but the maintainers of the thunar plugin has pointed to this page. [Thunar-archive-plugin/issues/1](https://gitlab.xfce.org/thunar-plugins/thunar-archive-plugin/-/issues/1))

On [Thunar-archive-plugin/issues/10](https://gitlab.xfce.org/thunar-plugins/thunar-archive-plugin/-/issues/10), a hacky solution is suggested, but It doesn't work. The following code sort of work, but it shows a dialog instead of just extracting to the current folder.

```
        cd "$folder"
        for name in "$@";
        do exec xarchiver --multi-extract "$@"
        done
        ;;
```

Can this be fixed? Alternatively, an "extract each archive to separate folders" right click option may be useful. Thanks!

**Comment by ib** [comment]
Your code example (hacky solution) is broken. Line 3 should be: `do xarchiver --multi-extract "$name"`.

I'll change the "Extract Here" behavior starting with the next xarchiver version to:
```
extract-here)
	cd "$folder"
	for archive in "$@"; do
		xarchiver --ensure-directory "$archive"
	done
	;;
```
This will then support both single and multi-file extraction.

I'll also change the "Extract To" behavior to support both single and multi-file extraction.
