### ISSUE TITLE
Add "Extract archive here, autodetect subfolder" option

### ISSUE THREAD

**Issue by micrococo** [ib/xarchiver#18]
Hi.

I'd like to have this option already available for KDE's Ark added to Xarchiver. You never know whether an archive has a subfolder inside or a bunch of files without checking its content first.

Thanks in advance.

**Comment by ib** [comment]
Please explain what such an option should exactly do.

**Comment by micrococo** [comment]
Sorry for the poor description of the request. Most of the times tarballs have folder inside and then the files are into that folder¹. But sometimes there are many files in the root level and when you choose extract-here you extract them all in the target directory², so you can end with a bunch of files mixed with the files that were in that directory.

1. archive.tar.gz with all the files inside a folder

   folder
   ├ file1
   ├ file2
   └ file3

2. archive.tar.gz with all the files at root level

   file1
   file2
   file3

Ark's "Extract archive here, autodetect subfolder" checks if the contents of the archive are in a folder, and if it isn't the case it makes the folder and extracts the files on it. The automatically created folder has the same archive name minus the extension, and if the folder already exists it adds numeric suffixes (1), (2), ...

**Comment by micrococo** [comment]
Thank you very much for implementing this!

**Comment by aloboa** [comment]
"Extract here" does not ensure a containing folder. Please let the user have an option
in Preferences to enforce this (I understand other users might prefer the current behavior)
Thanks

**Comment by ib** [comment]
@aloboa 
If you are referring to the 'extract-here' of the plugin, see pull request #63. A (run-time) preference is not possible because it is handled by an external script.

**Comment by jwoodard80** [comment]
I realize this is an old thread. However, I wonder if this couldn't be phrased more clearly. Currently it gives no real indication that a folder will be created.

From "Extract Archive Here, detect subfolder"
To "Extract Archive to Folder, detect subfolder"

**Comment by ib** [comment]
@jwoodard80

Where or when is "Extract Archive Here, detect subfolder" displayed? It does not exist in xarchiver.

**Comment by jwoodard80** [comment]
I misread this..... my apologies, please remove the comment
