### ISSUE TITLE
7z missed option -w/tmp

### ISSUE THREAD

**Issue by LinuxOpa** [ib/xarchiver#180]
Ubuntu 22.04.3
xarchiver 0.5.4.17:

Entered as directory for temporary files: /tmp

but in the command line temp is not used: Command: /usr/bin/7z d -bd -spd -y /intenso2/safe.7z 'safe/sda_230914-0708.img/' ...

There is a "-w/tmp" missing in the command

in ./.config/xarchiver there is: preferred_temp_dir=/tmp

**Comment by ib** [comment]
The directory for temporary files is the directory that xarchiver itself uses for its temporary files during work.

**Comment by LinuxOpa** [comment]
thanks!

**Comment by ib** [comment]
There seems to be nothing wrong with using the preferred_temp_dir also for archivers that offer such an option, but this requires some investigation.

**Comment by ib** [comment]
After testing this feature, I decided **not** to implement it.

When specifying a temporary working directory for an archiver, operations such as adding and deleting are initially performed using a temporary copy. Additional time is then required to copy to the destination.

This may be useful when writing to a very slow target filesystem or when the target filesystem does not have enough free space, but in general using such a _slowdown option_ is probably not desirable.
