### ISSUE TITLE
[Bug] `Ensure a containing directory` doesn't work on `Selected files` selected

### ISSUE THREAD

**Issue by kuraga** [ib/xarchiver#181]
When in the `Extract files` dialog,
the `Selected files` radio button is selected, then then `Ensure a containing directory` is (visually) checked and disabled.
But really, the containing directory isn't created!

More precisely, "(visually) checked" above is "(visually) not changed on disabling".
So, at dialog start it's (visually) checked.
You can select `All files`, uncheck `Ensure a containing directory`, select `Selected files` - then it would be (visually) unchecked and disabled.
But the containing directory isn't created.

P.S. Everything is OK in `All files` case.

xarchiver 0.5.4.21

**Comment by ib** [comment]
A disabled item means that the option is not available.

**Comment by kuraga** [comment]
> A disabled item means that the option is not available.

@ib, uncheck it before?

**Comment by kuraga** [comment]
@ib, would you accept PR on this?
Current behavior confuses due to its incorrectness.

**Comment by ib** [comment]
Only if this would apply to **all** check and radio buttons, and if the current values would be saved in case of deactivation, the buttons would be displayed without check marks and would be properly restored to their current state afterwards. In addition, those buttons whose default behavior is the checked state despite being disabled would have to keep their check mark (or get one if currently unchecked).

This is anything but trivial.
