### ISSUE TITLE
Security Vulnerability report

### ISSUE THREAD

**Issue by febinrev** [ib/xarchiver#183]
I am a security researcher, and I have found a security vulnerability in Xarchiver and the vulnerability is capable of Remote Command Execution upon extracting a crafted Archive.

I would like to safely disclose the details about the vulnerability to the devs, please provide me with the right contact information to report the bug.

My Email: [febin.sec@gmail.com](mailto:febin.sec@gmail.com)

Thanks,
Febin

**Comment by ib** [comment]
I've enabled private vulnerability reporting for the repository. You should be able to report at https://github.com/ib/xarchiver/security. If it doesn't work, please let me know. I'll have to re-check the configuration for private vulnerability reporting then.

**Comment by febinrev** [comment]
> I've enabled private vulnerability reporting for the repository. You should be able to report at https://github.com/ib/xarchiver/security. If it doesn't work, please let me know. I'll have to re-check the configuration for private vulnerability reporting then.

Hey, just reported the vulnerability there.

**Comment by ib** [comment]
Fixed. Thank you for reporting.

**Comment by febinrev** [comment]
Thanks!
