### ISSUE TITLE
Release tarball

### ISSUE THREAD

**Issue by nunotexbsd** [ib/xarchiver#187]
Is it possible to create a release tarball instead of auto-generated one?

More info on:
https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/
https://docs.freebsd.org/en/books/porters-handbook/book/#makefile-master_sites-github

Thanks

**Comment by ib** [comment]
I release by [tagging](https://github.com/ib/xarchiver/tags).

What are the problems with it?

**Comment by nunotexbsd** [comment]
That .tar.gz is a auto-generated tarball, created each time that we fetch:
https://github.com/ib/xarchiver/archive/refs/tags/0.5.4.22.tar.gz

Take for example:

https://github.com/jordansissel/xdotool/releases/tag/v3.20211022.1

where we have a fixed tarball:
https://github.com/jordansissel/xdotool/releases/download/v3.20211022.1/xdotool-3.20211022.1.tar.gz

This complies with:
https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

and it's very usefull for packagers.

**Comment by ib** [comment]
See https://github.com/ib/xarchiver/issues/175 and https://github.com/ib/xarchiver/issues/176.
