### ISSUE TITLE
Segfault when navigating one level up in zst archive

### ISSUE THREAD

**Issue by radioactiveman** [ib/xarchiver#189]
Steps to Reproduce
1. Download this zst archive: https://pkg.freebsd.org/FreeBSD:14:amd64/latest/All/json-glib-1.8.0.pkg
2. Open it with xarchiver
3. Navigate into /usr directory
4. Navigate one level up

Behaviour
- xarchiver crashes due to a segfault
- Navigating back to root with the "Back" button works

System Information
- Arch Linux
- xarchiver-gtk3 0.5.4.22

**Comment by pclinuxer** [comment]
Hello:

Reproduced as described by OP.
ie: segfault crash on one level up from `/usr` dir and working 'Back' button

Running Devuan Beowulf with a backported kernel and `xarchiver 0.5.4.14`.
```
~$ uname -a
Linux devuan 5.10.0-0.deb10.16-amd64 #1 SMP Debian 5.10.127-2~bpo10+1 (2022-07-28) x86_64 GNU/Linux
~$ 
```
Rolling `dmesg` printout
```
[Feb 5 09:15] xarchiver[11832]: segfault at 20 ip 0000557db746572e sp 00007fffdac1acd0 error 4 in xarchiver[557db7457000+30000]
[  +0.000015] Code: 4c 89 f2 48 89 c7 49 89 c5 e8 4e 2e ff ff 85 c0 0f 85 56 01 00 00 48 8b 3c eb 48 8b b7 a8 00 00 00 e8 c6 84 ff ff 48 8b 3c eb <48> 8b 70 20 49 89 c5 e8 66 c3 01 00 49 8b 7d 20 e8 2d 89 ff ff 48

```
HTH

Best,
PCL

**Comment by ib** [comment]
@radioactiveman Thank you for reporting. It is fixed now.

**Comment by radioactiveman** [comment]
Thank you for the fast fix, I can confirm it's working now. :+1:
