### ISSUE TITLE
Unable to handle ZIP archives with Russian characters

### ISSUE THREAD

**Issue by mh466lfa** [ib/xarchiver#200]
Both the archive's name and the names of the files in the archive contain Russian characters. If I rename the archive to get rid of the Russian characters, it still fails to extract the archive's content (which is full of file names with Russian characters).

Note: I can extract it in the terminal with `unzip` just fine.

**Comment by ib** [comment]
How am I supposed to be able to make any use of it if all essential information (xarchiver version, language settings for both file system and shell, error message) is missing?

**Comment by mh466lfa** [comment]
> How am I supposed to be able to make any use of it if all essential information (xarchiver version, language settings for both file system and shell, error message) is missing?

You can consider that I'm made this up. Goodbye.

p/s: It's the `PABCWork.NET` directory of PascalABC.NET on Windows compressed into ZIP by WinRAR. System is FreeBSD with XFCE4. Language is en-US.UTF-8. Xarchiver is latest install from binary package (see freshports.org for more details, as I'm not on this system anymore so I can't give you any further information).

**Comment by Curculigo** [comment]
I suspect that it's either `libarchive` or `7-zip` (`p7zip` on MX Linux). But `libarchive` is more likely.

**Comment by kuraga** [comment]
https://github.com/libarchive/libarchive/issues/2307, https://github.com/libarchive/libarchive/pull/2240?

But strange issues are new. Remember issues like this kinda... ten years ago :smile:
