### ISSUE TITLE
segfault when extracting .gz file xa_toggle_relative_path_radio (button=<optimized out>, extract_dialog=0x555555786080) at ./src/extract_dialog.c:88

### ISSUE THREAD

**Issue by Pentium4User** [ib/xarchiver#202]
Hello!

I run xarchiver 1:0.5.4.23-1 amd64 on Debian Unstable (with mwm window manager, if that is relevant).

ftp://ftp.isc.org/usenet/control/other.ctl/checkgroups.2024.gz
is the file that creates the crash.

I opened it in xarchiver and then used the extract menu command.

kind regards

`
(gdb) r /tmp/mozilla_m0/checkgroups.2024.gz
Starting program: /usr/bin/xarchiver /tmp/mozilla_m0/checkgroups.2024.gz
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5c006c0 (LWP 21661)]
[New Thread 0x7fffefe006c0 (LWP 21662)]
[New Thread 0x7ffff52006c0 (LWP 21663)]
[New Thread 0x7fffece006c0 (LWP 21664)]
[New Thread 0x7fffe7e006c0 (LWP 21665)]
[New Thread 0x7fffe74006c0 (LWP 21667)]
[New Thread 0x7fffe6a006c0 (LWP 21668)]
[Detaching after fork from child process 21669]
[Detaching after fork from child process 21670]
[Detaching after fork from child process 21671]
[Detaching after fork from child process 21672]
[Detaching after vfork from child process 21674]
[Thread 0x7fffe74006c0 (LWP 21667) exited]
[Thread 0x7fffe7e006c0 (LWP 21665) exited]

Thread 1 "xarchiver" received signal SIGSEGV, Segmentation fault.
0x0000555555568dbb in xa_toggle_relative_path_radio (button=<optimized out>, extract_dialog=0x555555786080) at ./src/extract_dialog.c:88
warning: 88     ./src/extract_dialog.c: Datei oder Verzeichnis nicht gefunden
(gdb) 
(gdb) 
(gdb) trace
Tracepoint 1 at 0x555555568dbb: file ./src/extract_dialog.c, line 88.
(gdb) quit
A debugging session is active.

        Inferior 1 [process 21658] will be killed.

Quit anyway? (y or n) y
`

**Comment by ib** [comment]
What does your extraction dialog look like and which program is responsible for gzip files (`xarchiver -i` and version of the program displayed there)?

**Comment by Pentium4User** [comment]
No extraction dialog is being shown.
`
gzip:
  /usr/bin/gzip
gzip 1.12
`

**Comment by ib** [comment]
So it crashes when you click the icon to extract files?

**Comment by Pentium4User** [comment]
exactly.

**Comment by ib** [comment]
Could you please look in your `xarchiverrc` in the config directory and tell me the value of `full_path`? Then change it to 0 and try again.

**Comment by Pentium4User** [comment]
Am 23.09.2024 um 05:29:32 Uhr schrieb Ingo Brückl:

> Could you please look in your `xarchiverrc` in the config directory
> and tell me the value of `full_path`? Then change it to 0 and try
> again.

Thanks, that fixed it. It was set to 1.

**Comment by ib** [comment]
> Thanks, that fixed it. It was set to 1.

Nevertheless, not handling arbitrary configuration settings is a bug. Thanks for reporting this.
