### ISSUE TITLE
Latgalian language translation 

### ISSUE THREAD

**Issue by ArtchyZ** [ib/xarchiver#204]
Hello,

Please add Latgalian language translation. File is attached. 
[ltg.zip](https://github.com/user-attachments/files/17893753/ltg.zip)

Thanks.

**Comment by ib** [comment]
The language file has been [added](https://github.com/ib/xarchiver/commit/cddf3d5094aebf6b0326dd56ceb9b93a3a8f9139):

```
ltg   ( 77%)  243 translated messages, 46 fuzzy, 23 untranslated
```

Changes can be made on [Weblate](https://hosted.weblate.org/projects/xarchiver/translations/ltg/).
