### ISSUE TITLE
Spanish translation update

### ISSUE THREAD

**Issue by micrococo** [ib/xarchiver#21]
Hi.

This is the Spanish translation update for version 0.5.4.10.
[es.zip](https://github.com/ib/xarchiver/files/1032846/es.zip)

Greetings.

**Comment by ib** [comment]
Thanks a lot. It will be in coming 0.5.4.11.

**Comment by ib** [comment]
There will be a few new messages. Do you want to translate them before the next release?
```
msgid "%d file"
msgid_plural "%d files"
```
```
msgid "Archiver executable:"
```
(This means the executable found and used to uncompress the archive.)
```
msgid "Checksum"

msgid "Date and Time"

msgid "Original Size"

msgid "Unsupported binary format!"

msgid "and"
```
```
msgid "Check Type"
msgid "Streams/Blocks/Padding"
```
(These are **xz** columns.)
```
msgid "Occupancy"
msgid "Saving"
```
Besides the _ratio_ (compressed size/uncompressed size) there is now _occupancy_ (ratio * 100) in percentage terms and _saving_ (100% - occupancy).

**Comment by micrococo** [comment]
Hi.

Sure, and thanks for the tips. There you are:

```
msgid "%d file"
msgid "%d fichero"

msgid_plural "%d files"
msgid_plural "%d ficheros"

msgid "Archiver executable:"
msgid "Ejecutable del programa de compresión:"

msgid "Checksum"
msgid "Suma de verificación"

msgid "Date and Time"
msgid "Fecha y hora"

msgid "Original Size"
msgid "Tamaño original"

msgid "Unsupported binary format!"
msgid "¡Formato binario no soportado!"

msgid "and"
msgid "y"

msgid "Check Type"
msgid "Tipo de comprobación"

msgid "Streams/Blocks/Padding"
msgid "Flujos/Bloques/Relleno"

msgid "Occupancy"
msgid "Tasa de uso"

msgid "Saving"
msgid "Reducción"
```

Greetings.

**Comment by ib** [comment]
Congratulations, the Spanish translation is 100% complete now.

BTW, I saw - by chance - a probable wrong translation:
```
msgid "file1 ... fileN"
msgstr "archivo1 ... archivoN"
```
These are _files_ to be added to an archive, so rather than _archivo_  it should be _fichero_ or the like?

**Comment by micrococo** [comment]
_Archivo_ and _fichero_ are used interchangeably, but I think that _archivo_ is used more frequently when talking about compressed archives. So yes, it seems okay to use _fichero_ here to maintain consistency with the rest of the translation. I overlooked it when I updated the translation.

**Comment by ib** [comment]
Due to issue #23, there are a few new terms:
```
archiver
archiving
compression
front end
front-end
frontend
```
If there are alternative forms for any term, provide them all (like the three alternatives for English _front end_ - I did two German translations for English _compression_). If there are no alternative forms, a single translation is okay as well. Translation doesn't have to be one-to-one, but should cover possible meanings or spellings.

**Comment by micrococo** [comment]
Hi.

If keywords have to be, well, just one word, the first column is fine and enough. If more than one word is allowed as a keyword, the longer version, when available, is more descriptive.

```
archiver		archivador	compresor de ficheros
archiving		archivado		compresión de ficheros
compression	compresión		
front end		interfaz		interfaz de usuario
front-end		interfaz		interfaz de usuario
frontend		interfaz		interfaz de usuario
```

**Comment by ib** [comment]
Although spaces are allowed in keywords, I think that a user will type only short catchwords. It may only be relevant for alternative spellings like _front end_  / _frontend_ (and I'm actually not really sure about that, but I found out that there is no extra benefit adding _front-end_). To cut a long story short, I think adding
```
archivado
archivador
compresión
compresor
interfaz
```
as Spanish keywords seems best.

**Comment by ib** [comment]
And an other one (that was already translated, but obsolete so far). Is it okay?
```
msgid "The archiver doesn't support this feature!"
msgstr "¡El programa de compresión no soporta esta funcionalidad!"
```

**Comment by micrococo** [comment]
It looks good to me.

**Comment by ib** [comment]
There will be a new preference option on the _Advanced_ page:
```
msgid "Open archive files with:"
```

**Comment by micrococo** [comment]
Hi. Just to be sure, "Open archive files with" means "open compressed files with...", isn't it?

```
msgid "Open archive files with:"
msgstr "Abrir los archivos comprimidos con:"

msgid "Default custom command:"
msgstr "Comando personalizado predefinido:"
```

**Comment by ib** [comment]
> Just to be sure, "Open archive files with" means "open compressed files with...", isn't it?

Yes. This means all files that xarchiver can open.

And in the meantime, there is another one (a new xarchiver command line option):
```
msgid "Show found command line programs to be used and exit"
```
(I'll do the necessary line break and spacing.)

**Comment by micrococo** [comment]
```
msgid "Show found command line programs to be used and exit"
msgstr "Mostrar los programas de línea de comandos para usar encontrados y terminar"
```
