### ISSUE TITLE
Hightlight the initially selected item in Preferences

### ISSUE THREAD

**Issue by micrococo** [ib/xarchiver#22]
Hi.

When you open the Preferences dialog, there is no option selected in the left side list. In addition, the current options panel displayed is the third one (Advanced), not the first one. I think that the first options panel should be the default selected and the item in the list should be highlighted too.

Greetings.

**Comment by ib** [comment]
This is a known bug on my to-do list. Maybe in 0.5.4.11.

**Comment by ib** [comment]
Fixed.

**Comment by micrococo** [comment]
Thanks!
