### ISSUE TITLE
Adding keywords to xarchiver's desktop file

### ISSUE THREAD

**Issue by apoleon** [ib/xarchiver#23]
Please consider to add keywords to xarchiver's desktop file like

Keywords=GTK;archiver;frontend;compression;zip;bz2;7z;gzip;deb;rpm;arj;lzma;rar;xz;

This will allow modern desktop environments to provide better search results to users.

**Comment by ib** [comment]
Are _zip;bz2;7z;gzip;deb;rpm;arj;lzma;rar;xz;_ meant to be filename extensions or program names?

**Comment by apoleon** [comment]
Am 12.06.2017 um 00:12 schrieb ib:
> Are /zip;bz2;7z;gzip;deb;rpm;arj;lzma;rar;xz;/ meant to be filename
> extensions or program names?

That's just a suggestion and feel free to adjust the values as you see
fit. Since xarchiver supports all these file types it makes sense to
promote them with Keywords. For instance with Gnome 3 and Gnome Shell it
would be more likely that xarchiver was one of the first search hits, if
someone typed in just "gzip". So you don't have to know the real program
name but just the feature or function the program supports.

**Comment by ib** [comment]
I've chosen the following keywords:
```
GTK;archiver;archiving;compression;front end;front-end;frontend;7-zip;7z;7za;7zip;7zr;ar;arj;bunzip2;bz2;bzip2;compress;cpio;deb;gtar;gunzip;gz;gzip;jar;lha;lsar;lz;lz4;lzh;lzip;lzma;lzo;lzop;rar;rar4;rar5;rpm;tar;unar;unarj;unrar;unzip;xz;zip;
```
Further proposals are welcome.
