### ISSUE TITLE
Auto-reconfiguration of xarchiver's build system

### ISSUE THREAD

**Issue by apoleon** [ib/xarchiver#24]
Please consider to support autoreconf. At the moment xarchiver will fail to build from source if someone tries to recreate the autoconf configuration files. Currently it fails with the following output:

aclocal: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:38: installing './compile'
configure.ac:30: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './AUTHORS' not found
src/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
dh_autoreconf: autoreconf -f -i returned exit code 1

**Comment by ib** [comment]
What's the advantage over the provided autogen.sh script?

**Comment by apoleon** [comment]
Am 11.06.2017 um 22:41 schrieb ib:
> What's the advantage over the provided autogen.sh script?

autoreconf is the recommended way to recreate the autotools build system
with a single command. It also takes various environment variables into
account and for instance "just works" on Debian systems without the need
to call a separate script.

https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoreconf-Invocation.html

**Comment by apoleon** [comment]
By the way the autogen.sh script fails with

./autogen.sh: 3: set: Illegal option -o pipefail

which apparently requires bash. I suggest to make it shell-independent
at least.

**Comment by wdlkmpx** [comment]
Just ran autoreconf in a debian-based os (with bash as the default shell), it failed. autogen.sh did work.

Sometimes autoreconf fails for whatever reason, and that's when the autogen.sh script comes in handy. The first few lines do seem to be bashisms, and should replaced..

**Comment by ib** [comment]
The "wontfix" refers to the autoreconf request, autogen.sh will be fixed to become shell-independent.

**Comment by ib** [comment]
The script has been fixed.
