### ISSUE TITLE
xarchiver: Overwrites existing files without warning

### ISSUE THREAD

**Issue by apoleon** [ib/xarchiver#25]
I am hereby forwarding Debian bug #757600. 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757600

This is still reprocubible with 0.5.4.10. Steps to reproduce:

1. Extract Packages.gz using Xarchiver, creating a file 'Packages' in
the same directory.
2. Modify the Packages file to make changes obvious by running
  echo "CHANGED" >> Packages
3. Run Xarchiver again, click extract files, leave the 'Overwrite
existing files' option clear, then click the Extract button.
4. The 'Packages' file is overwritten without warning.

**Comment by ib** [comment]
Fixed.
