### ISSUE TITLE
xarchiver 0.5.4.11 fails to build from source

### ISSUE THREAD

**Issue by apoleon** [ib/xarchiver#27]
Hi,

I tried the latest release but it fails to build from source. System: Debian GNU/Linux, sid, amd64. The error is

 open-with-dlg.c:122:42: error: unknown type name 'GtkObject'

Relevant output below (hopefully)

gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wno-unused-parameter -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DHTMLDIR=\"/usr/share/doc/xarchiver\" -DLOCALEDIR=\"/usr/share/locale\" -DPIXMAPSDIR=\"/usr/share/pixmaps/xarchiver\" -Wno-deprecated-declarations -g -O2 -fdebug-prefix-map=/build/xarchiver-0.5.4.11=. -fstack-protector-strong -Wformat -Werror=format-security -c -o xarchiver-new_dialog.o `test -f 'new_dialog.c' || echo './'`new_dialog.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wno-unused-parameter -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DHTMLDIR=\"/usr/share/doc/xarchiver\" -DLOCALEDIR=\"/usr/share/locale\" -DPIXMAPSDIR=\"/usr/share/pixmaps/xarchiver\" -Wno-deprecated-declarations -g -O2 -fdebug-prefix-map=/build/xarchiver-0.5.4.11=. -fstack-protector-strong -Wformat -Werror=format-security -c -o xarchiver-open-with-dlg.o `test -f 'open-with-dlg.c' || echo './'`open-with-dlg.c
open-with-dlg.c:122:42: error: unknown type name 'GtkObject'
 static void xa_destroy_open_with_dialog (GtkObject *object, Open_with_data *data)
                                          ^~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:28:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from open-with-dlg.c:20:
open-with-dlg.c: In function 'xa_create_open_with_dialog':
open-with-dlg.c:460:69: error: 'xa_destroy_open_with_dialog' undeclared (first use in this function)
  g_signal_connect (G_OBJECT (data->dialog1), "destroy",  G_CALLBACK(xa_destroy_open_with_dialog),data);
                                                                     ^
/usr/include/glib-2.0/gobject/gsignal.h:475:60: note: in definition of macro 'g_signal_connect'
     g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), NULL, (GConnectFlags) 0)
                                                            ^~~~~~~~~
open-with-dlg.c:460:58: note: in expansion of macro 'G_CALLBACK'
  g_signal_connect (G_OBJECT (data->dialog1), "destroy",  G_CALLBACK(xa_destroy_open_with_dialog),data);
                                                          ^~~~~~~~~~
open-with-dlg.c:460:69: note: each undeclared identifier is reported only once for each function it appears in
  g_signal_connect (G_OBJECT (data->dialog1), "destroy",  G_CALLBACK(xa_destroy_open_with_dialog),data);
                                                                     ^
/usr/include/glib-2.0/gobject/gsignal.h:475:60: note: in definition of macro 'g_signal_connect'
     g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), NULL, (GConnectFlags) 0)
                                                            ^~~~~~~~~
open-with-dlg.c:460:58: note: in expansion of macro 'G_CALLBACK'
  g_signal_connect (G_OBJECT (data->dialog1), "destroy",  G_CALLBACK(xa_destroy_open_with_dialog),data);
                                                          ^~~~~~~~~~
At top level:
open-with-dlg.c:57:13: warning: 'xa_app_free' defined but not used [-Wunused-function]
 static void xa_app_free (App *app, gpointer user_data)
             ^~~~~~~~~~~
Makefile:748: recipe for target 'xarchiver-open-with-dlg.o' failed

**Comment by ib** [comment]
Thanks for reporting. Should be fixed now.
