### ISSUE TITLE
Add lrzip to the supported compressed files

### ISSUE THREAD

**Issue by jristz** [ib/xarchiver#28]
Actually hte contextual menu for select the specific compression format and the menu for the default compressed format and also the uncompression not support lrzip [1] where even package managers (like pacman [not by default]) support compression as lrzip so it could be nice support this compression option

[1] http://ck.kolivas.org/apps/lrzip/

EDIT: also please update the Changelog file to know what new,

**Comment by ib** [comment]
> also please update the Changelog file to know what new

You have to read the commit messages.
