### ISSUE TITLE
Xarchiver is not handling rar files

### ISSUE THREAD

**Issue by Jorge-Gonzalez** [ib/xarchiver#3]
Hi, I'm using LXLE and have unrar installed so I can unrar files from the command line, but not from Xarchiver.

Thanks.

**Comment by ib** [comment]
I have installed unrar, too, and it works fine with xarchiver. Is unrar in a directory in your PATH?

What does cmd-line output say?

**Comment by Jorge-Gonzalez** [comment]
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

which unrar
/usr/bin/unrar


Date: Sat, 25 Jul 2015 10:05:59 -0700

**Comment by ib** [comment]
> What does cmd-line output say?

By this, I meant xarchiver's option to 'store archiver output'. You should see then what xarchiver called and what went wrong.

**Comment by Jorge-Gonzalez** [comment]
Opening a rar file shows nothing in the files list, and the option for the command line output is always disabled, in which scenario is this option available? Tell me if there is some test you want me to do, and I would like to know if there is a config file for triggering the command?

Regards

        
 
              
Date: Sun, 26 Jul 2015 13:58:25 -0700

**Comment by ib** [comment]
Is it the option that is disabled or the menue entry?

You must enable the option first (Action -> Preferences -> Archive -> Store archiver output), then you can see the cmd-line output after having opened an archive. (Incidentally, this will result in a store_output=true in the xarchiverrc config file.)

BTW, what's your xarchiver version?

**Comment by ib** [comment]
Additional questions:

What version is your unrar (type: `unrar | grep "^UNRAR "`)?

What version is the archive you're trying to extract (type: `unrar l your.file.rar | grep "^Details: "`)?

**Comment by Jorge-Gonzalez** [comment]
unrar | grep "^UNRAR "
UNRAR 5.00 beta 8 freeware      Copyright (c) 1993-2013 Alexander Roshal

unrar l minimal_conky*.rar | grep "^Details: "
Details: RAR 4


Date: Tue, 28 Jul 2015 10:30:34 -0700

**Comment by Jorge-Gonzalez** [comment]
version: 
xarchiver 0.5.2svn-r29673


output: 

UNRAR 5.00 beta 8 freeware      Copyright (c) 1993-2013 Alexander Roshal


Extracting from /home/jorge/Descargas/greenie_openbox_suite_by_superjulius001-d3ft4id.rar

No files to extract



Date: Tue, 28 Jul 2015 02:49:13 -0700

**Comment by ib** [comment]
Well, I don't know about xarchiver 0.5.2svn-r29673, because the version I'm maintaining here is currently 0.5.4.4 which doesn't have any problems with either UNRAR 5.00 beta 8 nor the rar files you've mentioned.

xarchiver prior to version 0.5.3 couldn't handle rar v5, so you'd better use a version 4 unrar (http://www.rarlab.com/rar/unrarsrc-4.2.4.tar.gz seems to be the last v4 one) which should work with your xarchiver. Please report back.

Nevertheless, I've discovered some bugs with rar archives containing comments which I'm fixing right now. You are strongly encouraged to use the version I'm maintaining here if you're capable of compiling it yourself. (A ready-to-use configure script will be added soon.)

**Comment by ib** [comment]
No feedback. Issue closed.

**Comment by andreworg** [comment]
I seem to have found this very same issue, so I'm open to give you further info in case anybody wants to investigate further (xarchiver 0.5.3 from arch linux ARM, UNRAR 5.30 beta 4 freeware, archive details: RAR 4, solid, no rar comments AFAICT).  No problems when unrar is called from the CLI.

**Comment by ib** [comment]
Thanks for reporting.

With unrar 5.30 or later it's a different issue which has been fixed now.

Please keep in mind that xarchiver 0.5.3 is pretty old and that I'm only supporting this fork on github (currently version 0.5.4.5). So either use xarchiver from here or unrar 5.21 to fix your problem.

**Comment by andreworg** [comment]
I am sorry, I did not realize I wasn't running the latest code. Good to know and thanks for pointing out.

**Comment by ktrace** [comment]
> $ grep -i rar Trace.log | grep -v temporar
> execve("/usr/bin/xarchiver", ["xarchiver", "wc3x.sound.rdn-team.com.rar"], [/* 70 vars */]) = 0
> access("/usr/local/bin/rar", X_OK)      = -1 ENOENT (No such file or directory)
> access("/usr/bin/rar", X_OK)            = -1 ENOENT (No such file or directory)
> access("/bin/rar", X_OK)                = -1 ENOENT (No such file or directory)
> access("/opt/bin/rar", X_OK)            = 0
> stat("/opt/bin/rar", {st_mode=S_IFREG|0755, st_size=533488, ...}) = 0
> read(9, "\nRAR 5.30   Copyright (c) 1993-2"..., 4096) = 1071
> open("wc3x.sound.rdn-team.com.rar", O_RDONLY) = 11
> read(11, "Rar!\32\7\0;\320s\10\0\r\0\0\0\0\0\0\0\266\247t\300\220c\0\212\n\1\0\316"..., 4096) = 4096
> read(13, "\nRAR 5.30   Copyright (c) 1993-2"..., 1024) = 699

rar l <rarchive> work perfectly, but xarchiver can't show filelist. 
xarchicher 0.5.4

**Comment by ib** [comment]
@ktrace 
There is no support for buggy old version 0.5.4 here. Please use the most recent [release](https://github.com/ib/xarchiver/releases).
