### ISSUE TITLE
xarchiver can't open archives with a space followed by a "#" in the filename

### ISSUE THREAD

**Issue by chowbok** [ib/xarchiver#35]
As the description says, I can't open any archives that have a hash sign in them. I assume it's calling a script that is seeing them as comment markers.

**Comment by ib** [comment]
Please give an example and tell the version of xarchiver you are using.

Xarchiver has been tested to work with (all?) special characters in filenames.

**Comment by chowbok** [comment]
Using version 0.5.4.12. I'm running the following command:

xarchiver "test #1.zip"

And I get the following error:

zipinfo:  cannot find or open /home/kjs/temp/test , /home/kjs/temp/test .zip or /home/kjs/temp/test .ZIP.

**Comment by chowbok** [comment]
Okay, on further testing I see that it can't open files with a space followed by a hash sign, not just a hash sign. Sorry for the overly broad report.

**Comment by ib** [comment]
OK, now I can reproduce.
