### ISSUE TITLE
xarchiver-0.5.4.12 preferences ignored

### ISSUE THREAD

**Issue by fedan** [ib/xarchiver#40]
Select, unselect checkbox "Confirm deletion of files" ignored.
In archives tar.* (e.g. *.tar.gz, *.tar.bz2) always deleted *.gz or *.bz2.
Only *.tar remains.

**Comment by ib** [comment]
Sorry, I don't understand. Please explain more detailed.

**Comment by ktrace** [comment]
Here two different problems. 

Second problem: when open *.tar.gz (*.tar.bz2) xarchiver 'freezing' with message "open archive, please wait..." with no listing files in archive. It's infinite process. But on the HDD we have: file original.tar.gz(bz2) disappear and appear original.tar. It may be opened usual way with file listing inside. I see this problem right now and confirm it.

First problem: unselect checkbox "Confirm deletion of files" ignored. I can't confirm this issue. If I unselect checkbox "Confirm deletion of files" (Actions -> Preferences) files in archive deleted without confirmation (as expected).

**Comment by ib** [comment]
@ktrace 
> xarchiver 'freezing'

Depending on the content of a tar archive, opening may take a while. How many files does it contain?

> original.tar.gz(bz2) disappear

I cannot reproduce this. Actually, xarchiver doesn't touch the original, but creates an uncompressed working copy in the preferred temp directory.

Please provide:
* complete Cmd-line output
* your xarchiverrc
* output of `xarchiver -i` (from a terminal window)

**Comment by ktrace** [comment]
> I cannot reproduce this.
Let's check, if it distro-depened bug I retarget it in gentoo's bugzilla.

complete Cmd-line output:
> gzip: skipping: /home/user/very-important-database_20160630_144336_nosql_73bfbe9d.tar.gz does not exist
> [xarchiver]
> preferred_format=0
> prefer_unzip=true
> confirm_deletion=true
> sort_filename_content=false
> store_output=true
> icon_size=0
> show_archive_comment=false
> show_sidebar=true
> show_location_bar=true
> show_toolbar=true
> preferred_temp_dir=/tmp
> allow_sub_dir=0
> ensure_directory=false
> overwrite=true
> full_path=true
> touch=false
> fresh=false
> update=false
> store_path=false
> updadd=false
> freshen=false
> recurse=true
> solid_archive=false
> remove_files=false

output of xarchiver -i (from a terminal window)

> $ xarchiver -i
> xarchiver 0.5.4 ©  2005-2014 Giuseppe Torelli
> xarchiver 0.5.4.12 Ingo Brückl
> 7zip:
>   /usr/bin/7z
> arj:
>   /usr/bin/7z -tarj
> bzip2:
>   /usr/bin/bzip2
> compress:
>   /bin/uncompress
> cpio:
>   /bin/cpio
> deb:
>   /usr/bin/ar
> gzip:
>   /usr/bin/gzip
> lha:
>   /usr/bin/7z -tlzh
> lzma:
>   /usr/bin/lzma
> rar, rar5:
>   /opt/bin/rar
> rpm:
>   /bin/cpio
> tar:
>   /bin/tar
> xz:
>   /usr/bin/xz
> zip, epub, jar, oxt, xpi:
>   /usr/bin/unzip
>   /usr/bin/zip

**Comment by ktrace** [comment]
test archive: pgloader-2.3.2.tar.gz
$ ls ~/Downloads/pgloader*
/home/user/Downloads/pgloader-2.3.2.tar

**Comment by ib** [comment]
@ktrace 

I still cannot reproduce.

Does it happen with a small tar.gz/tar.bz2 as well?

When xarchiver is 'freezing', please see whether there is a directory named `xa-XXXXXX` in /tmp (XXXXXX denoting any combination of characters and numbers) and is anything inside this directory?

**Comment by ib** [comment]
@ktrace 

What does `/usr/bin/gzip -V` say?

**Comment by ktrace** [comment]
yes, it may be problem here
> /usr/bin/gzip -V
> pigz 2.3.4

**Comment by ib** [comment]
@ktrace

I can confirm that pigz is the problem.

While gzip does a decompression to stdout (`gzip -d foo.tar.gz -c > bar.tar`) without touching _foo.tar.gz_, pigz decompresses _foo.tar.gz_ to _foo.tar_ and produces any empty _bar.tar_.

So I'd say it's a compatibility bug in pigz.

**Comment by ktrace** [comment]
( gzip -c -d foo.tar.gz > bar.tar ) work with both versions, here workaround.

but i create issue https://github.com/madler/pigz/issues/51

**Comment by ktrace** [comment]
madler close bug https://github.com/madler/pigz/issues/51 "work as documented"

**Comment by ib** [comment]
Well, it's incompatible with gzip then.

**Comment by ktrace** [comment]
maybe you may change option order? here strange situation - if both developers (you and madler) will not change anything - question were not solved.

**Comment by ib** [comment]
@ktrace 
You are using a script named `gzip` that is incompatible with `gzip`. Just make it compatible.

**Comment by ib** [comment]
> Just make it compatible.

For example, set `C=-c` if `[[ "${@/-c/}" != "$@" ]]` and call `pigz $C "$@"`.
