### ISSUE TITLE
Current pending operation is not reported

### ISSUE THREAD

**Issue by mirh** [ib/xarchiver#41]
Say I have to extract a big folder from an archive. 
I drag and drop this from inside the thing to thunar window...
\*nothing happens\*
After awhile the extracted folder finally appears, once finished. 
But in the meantime there's no way to realize xarchiver is even doing something (except maybe indirectly checking cpu usage - or repeating the action and being told that's already underway)

**Comment by ib** [comment]
So you open an archive with xarchiver and drag and drop a folder from inside the xarchiver window to a thunar window in order to store this folder inside the path the thunar window is showing?

**Comment by mirh** [comment]
Yes, exactly that. 
I would expect a status bar or something to tell current progress, in addition to underlining there's an ongoing operation at all.

**Comment by ib** [comment]
Should work now.

**Comment by mirh** [comment]
Cool. 
Though something which keeps track of actual progress (just like 7-zip on windows) wouldn't hurt too.
