### ISSUE TITLE
Load icons from the freedesktop icon theme

### ISSUE THREAD

**Issue by sixsixfive** [ib/xarchiver#42]
it would be nice if xarchiver would integrate the freedesktop icon theme for xarchiver-add and xarchiver-extract

![screenshot from 2018-01-01 23-05-09](https://user-images.githubusercontent.com/3780774/34474709-546b9e12-ef48-11e7-83d9-2397b5e4fb4b.png)

**Comment by ib** [comment]
Where would I find this icon theme and these icons?

**Comment by sixsixfive** [comment]
the icon theme used in the screenshot can be found here: https://github.com/sixsixfive/Monotone

**Comment by ib** [comment]
Should work now.

**Comment by ib** [comment]
I've just emailed you in private via gmail.
