### ISSUE TITLE
0.5.4.12 hangs when opening an archive

### ISSUE THREAD

**Issue by landryb** [ib/xarchiver#47]
I'm trying to update xarchiver to 0.5.4.12 on OpenBSD, last known working version is 0.5.4.8. In later versions, opening an archive only shows a black window, busy looping on something. Same thing if opening the archive from the started UI, or opening it from the cmdline.

Debugging with gdb shows that xa_process_stdout/xa_process_stderr keep being called even when all the stdout/stderr content has been parsed, so maybe something isnt properly drained somewhere ? Or an error condition is not handled ?

On top of this i'd remove the 3 occurences of
```
while (gtk_events_pending())
               gtk_main_iteration();
```

Which seem deeply wrong to me.

**Comment by ib** [comment]
Which archive type are you trying to open?
Which OpenBSD program is responsible for opening it (`xarchiver -i`)?

> Or an error condition is not handled ?

Depending on how OpenBSD behaves that likely might be.

I can provide you with patches to track that issue down, if you are willing to assist.

>On top of this i'd remove the 3 occurences of
>```
>while (gtk_events_pending())
>               gtk_main_iteration();
>```
This allows handling GTK events while the command line background processes are running.

**Comment by landryb** [comment]
It happens whatever archive type i try to open, zip or tgz here. tracing with gdb, it seems there are race conditions in xa_process_stdout/xa_process_stderr, and gio keeps calling them with cond=G_IO_IN (so there is data to read) but the lines are all empty. I tried adding some handling for status=G_IO_STATUS_EOF (ie shutting down the gio channel) but failed to have something reliable, it's as if output/stderr lines were in a random order.

It seems on OpenBSD, gio first calls xa_process_stdout, status ie EOF, line is null, then i get the lines data so status is G_IO_STATUS_NORMAL (but sometimes not all of them), and then and endless loop of calls with G_IO_IN but g_io_channel_read_line() keeps returning EOF.

I can test patches of course, but i'm pretty sure if you try it in a VM you'll quickly reproduce it :)

The archivers detection works fine.
```
$./src/xarchiver -i                                                                                                                                   
xarchiver 0.5.4 ©  2005-2014 Giuseppe Torelli
xarchiver 0.5.4.12 Ingo Brückl
7zip:
  /usr/local/bin/7z
arj:
  /usr/local/bin/7z -tarj
bzip2:
  /usr/local/bin/bzip2
compress:
  /usr/bin/compress
cpio:
  /bin/cpio
deb:
  /usr/bin/ar
gzip:
  /usr/bin/gzip
lha:
  /usr/local/bin/7z -tlzh
lz4:
  /usr/local/bin/lz4
lzma:
  /usr/local/bin/lzma
rar, rar5:
  /usr/local/bin/7z -trar
  /usr/local/bin/7z -trar5
rpm:
  /bin/cpio
tar:
  /usr/local/bin/gtar
xz:
  /usr/local/bin/xz
zip, epub, jar, oxt, xpi:
  /usr/local/bin/unzip
  /usr/local/bin/zip

```

**Comment by ib** [comment]
> it's as if output/stderr lines were in a random order

They are.

> I can test patches of course, but i'm pretty sure if you try it in a VM you'll quickly reproduce it :)

I could, if I had a VM. :)

Please apply the attached patch, __unset__ "Store archiver output"  and redirect stderr to a log file when calling xarchiver. Please open something simple, like this attachment.

Hopefully, I'll get an idea from it.

[issue47.zip](https://github.com/ib/xarchiver/files/1713601/issue47.zip)

**Comment by landryb** [comment]
Well, i more or less had a similar local diff, and here's what it does:
```
# command: [/usr/local/bin/unzip -Z -l /tmp/mozilla_landry0/issue47.zip]
# creating channels...
# spawning done.
# [Archive:  /tmp/mozilla_landry0/issue47.zip] read from stdout (1)
# status is normal, interating... 

(xarchiver:40175): GLib-CRITICAL **: g_strchomp: assertion 'string != NULL' failed
# [(null)] read from stderr (2)

(xarchiver:40175): GLib-CRITICAL **: g_strchomp: assertion 'string != NULL' failed
# [(null)] read from stderr (2)

(xarchiver:40175): GLib-CRITICAL **: g_strchomp: assertion 'string != NULL' failed
# [(null)] read from stderr (2)

```
And then it goes in an infinite loop, for some reason gio keeps telling there's data to read on stderr.

Fwiw it's easy to build an OpenBSD vm in virtualbox, you only need maybe 2 or 3Go to install X and xarchiver dependencies :)

**Comment by ib** [comment]
> And then it goes in an infinite loop, for some reason gio keeps telling there's data to read on stderr.

Let's figure out what it is telling else. (New patch to be applied on fresh master checkout.)

[issue47.zip](https://github.com/ib/xarchiver/files/1714791/issue47.zip)

> Fwiw it's easy to build an OpenBSD vm in virtualbox

Yeah, but there's plenty of other stuff to be done.

**Comment by landryb** [comment]
```
# command: [/usr/local/bin/unzip -Z -l /tmp/issue47.zip]
# creating channels...
# spawning done.
# watching stdout (0x11)
# [Archive:  /tmp/issue47.zip] read from stdout (1)
# status is normal, interating... 
# watching stderr (0x11)
# [nothing] read from stderr (2)
# watching stderr (0x11)
# [nothing] read from stderr (2)
# watching stderr (0x11)
# [nothing] read from stderr (2)
# watching stderr (0x11)
# [nothing] read from stderr (2)
# watching stderr (0x11)
```

If i comment out the stderr gio watcher creation, the same infinite loop happens on stdout:
```
# command: [/usr/local/bin/unzip -Z -l /tmp/issue47.zip]
# creating channels...
# spawning done.
# watching stdout (0x11)
# [Archive:  /tmp/issue47.zip] read from stdout (1)
# status is normal, interating... 
# child exited, status is 0 (1)
# process 0 ended: success
# watching stdout (0x11)
# [Zip file size: 1494 bytes, number of entries: 1] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [-rw-r-----  3.0 unx     4148 tx     1318 defX 18-Feb-11 20:59 issue47.patch] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [1 file, 4148 bytes uncompressed, 1318 bytes compressed:  68.2%] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [nothing] read from stdout (2)
# watching stdout (0x11)
# [nothing] read from stdout (2)
# watching stdout (0x11)
# [nothing] read from stdout (2)
# watching stdout (0x11)
```

**Comment by ib** [comment]
Thanks, I think I know now what's happening. A fix will follow in a few minutes.

**Comment by ib** [comment]
New patch to be applied on fresh master checkout. This should fix it. (Please provide log for me to check.)

[issue47.zip](https://github.com/ib/xarchiver/files/1715922/issue47.zip)

**Comment by landryb** [comment]
It is definitely better as it doesnt go into an infinite loop, but i get an error window "an error occurred while accessing the archive" and the archive content isnt listed in the UI. We're getting there :)
```
$./src/xarchiver /tmp/issue47.zip 2>&1 |tee /tmp/xarchiver.log
# command: [/usr/local/bin/unzip -Z -l /tmp/issue47.zip]
# creating channels...
# spawning done.
# watching stdout (0x11)
# [Archive:  /tmp/issue47.zip] read from stdout (1)
# status is normal, interating... 
# watching stderr (0x11)
# [nothing] read from stderr (2)
# no more stderr input, condition is 0x11
# process 2 ended: ERROR
# child exited, status is 0 (1)
# process 0 ended: success
# watching stdout (0x11)
# [Zip file size: 1547 bytes, number of entries: 1] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [-rw-r-----  3.0 unx     4579 tx     1371 defX 18-Feb-12 10:50 issue47.patch] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [1 file, 4579 bytes uncompressed, 1371 bytes compressed:  70.1%] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [nothing] read from stdout (2)
# no more stdout input, condition is 0x11
# process 1 ended: ERROR

```

**Comment by ib** [comment]
> It is definitely better as it doesnt go into an infinite loop

Sorry, but I've updated my comment and exchanged the patch while you were testing. Please get it again.

**Comment by landryb** [comment]
I see the change with the test on cond. With that latest patch, it seems *much* better, except the last character of a line output seems eaten, ie the zip containing 'issue47.patch' displays the file as 'issue47.patc', and if i try to right-click -> view it, it will fail to find it in the zip.
```
# command: [/usr/local/bin/unzip -Z -l /tmp/issue47.zip]
# creating channels...
# spawning done.
# watching stdout (0x11)
# [Archive:  /tmp/issue47.zip] read from stdout (1)
# status is normal, interating... 
# watching stderr (0x11)
# [nothing] read from stderr (2)
# no more stderr input, condition is 0x10
# process 2 ended: success
# child exited, status is 0 (1)
# process 0 ended: success
# watching stdout (0x11)
# [Zip file size: 1547 bytes, number of entries: 1] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [-rw-r-----  3.0 unx     4579 tx     1371 defX 18-Feb-12 10:50 issue47.patch] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [1 file, 4579 bytes uncompressed, 1371 bytes compressed:  70.1%] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [nothing] read from stdout (2)
# no more stdout input, condition is 0x10
# process 1 ended: success
# command: [/usr/local/bin/unzip -j -o /tmp/issue47.zip 'issue47.patc' -d /tmp/xa-SO8EEZ]
# creating channels...
# spawning done.
# watching stdout (0x1)
# [Archive:  /tmp/issue47.zip] read from stdout (1)
# status is normal, interating... 
# watching stderr (0x1)
# [caution: filename not matched:  issue47.patc] read from stderr (1)
# status is normal, collecting... 
# watching stderr (0x11)
# [nothing] read from stderr (2)
# no more stderr input, condition is 0x10
# process 2 ended: success
# watching stdout (0x11)
# [nothing] read from stdout (2)
# no more stdout input, condition is 0x10
# process 1 ended: success
# process 0 ended: ERROR
```

same thing if i open a tar.gz containing a dir named py-qwt/pkg, the ui will display two dirs, one with py-qw and the other with py-qwt, containing a dir with pk and a dir with pkg, etc etc
```
# command: [sh -c "/usr/bin/gzip -d '/home/landry/py-qwt-5.2.1.tgz' -c > xa-tmp.decompressed"]
# creating channels...
# spawning done.
# watching stdout (0x11)
# [nothing] read from stdout (2)
# no more stdout input, condition is 0x10
# process 1 ended: success
# watching stderr (0x11)
# [nothing] read from stderr (2)
# no more stderr input, condition is 0x10
# process 2 ended: success
# process 0 ended: success
# command: [/usr/local/bin/gtar -tvf '/tmp/xa-BJ8CEZ/xa-tmp.decompressed']
# creating channels...
# spawning done.
# watching stdout (0x11)
# [drwxr-xr-x landry/wsrc       0 2017-07-26 14:27 py-qwt] read from stdout (1)
# status is normal, interating... 
# watching stderr (0x11)
# [nothing] read from stderr (2)
# no more stderr input, condition is 0x10
# process 2 ended: success
# child exited, status is 0 (1)
# process 0 ended: success
# watching stdout (0x11)
# [-rw-r--r-- landry/wsrc     687 2017-07-26 14:23 py-qwt/Makefile] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [-rw-r--r-- landry/wsrc     128 2017-07-26 13:31 py-qwt/distinfo] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [drwxr-xr-x landry/wsrc       0 2017-07-26 14:27 py-qwt/pkg] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [-rw-r--r-- landry/wsrc    3899 2017-07-26 13:51 py-qwt/pkg/PLIST] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [-rw-r--r-- landry/wsrc     288 2017-07-26 14:19 py-qwt/pkg/DESCR] read from stdout (1)
# status is normal, interating... 
# watching stdout (0x11)
# [nothing] read from stdout (2)
# no more stdout input, condition is 0x10
# process 1 ended: success
```

but id say that's a different/separate issue than the hangs :)

**Comment by landryb** [comment]
much better if i remove the `g_strchomp()` call from the printf debugging lines, all is fine.

**Comment by ib** [comment]
> With that latest patch, it seems much better, except the last character of a line output seems eaten

:)
That's because of the debugging output and expected behavior.

The commit will follow.

**Comment by landryb** [comment]
Thanks, current master works fine now on OpenBSD !
