### ISSUE TITLE
Crash when directly extracting RPM archives

### ISSUE THREAD

**Issue by nsalguero** [ib/xarchiver#5]
Hi,

When running the command "xarchiver --extract-to [a_directory] [a_RPM_archive]", I get a segmentation fault whereas extracting from the GUI succeeds.  The provided patch corrects the problem.

Best regards,

Nico.
[xarchiver-0.5.4.6-fix-sigsegv-when-directly-extracting-rpm.patch.txt](https://github.com/ib/xarchiver/files/183107/xarchiver-0.5.4.6-fix-sigsegv-when-directly-extracting-rpm.patch.txt)

**Comment by ib** [comment]
Thanks for reporting. It is fixed now.
