### ISSUE TITLE
Xarchiver crash after adding third folder

### ISSUE THREAD

**Issue by Art-2** [ib/xarchiver#53]
I created 3 folders (A, B and C), each one containing 3 empty text files (x1.txt, x2.txt and x3.txt), when I try to create a .7z file Xarchiver crash with the last one.
All the folders and the .7z file are located  in the home directory.

![peek 17-03-2018 22-33](https://user-images.githubusercontent.com/12375357/37562710-9670e4e4-2a34-11e8-9d06-38a5527bf374.gif)

`GLib-CRITICAL **: g_string_insert_len: assertion 'len == 0 || val != NULL' failed`

Xarchive 0.5.4.13
Xubuntu 17.10

**Comment by ib** [comment]
Now that's what I call a bug report!

**Comment by ib** [comment]
Fixed.
