### ISSUE TITLE
The "Root" button sends to the last folder listed in the "Archive tree" if a folder is selected in this list

### ISSUE THREAD

**Issue by Art-2** [ib/xarchiver#54]
When selecting a folder from the "Archive tree" and try to go back by pressing the Root button I end in the last folder listed in the "Archive tree"
![peek 2018-03-20 15-51](https://user-images.githubusercontent.com/12375357/37684750-a390c058-2c56-11e8-949b-0a33a905599d.gif)

**Comment by ib** [comment]
Strangely enough, this only happens under GTK3, the GTK2 build works without errors.
It may take a while before I figure out why.

**Comment by ib** [comment]
Fixed.
