### ISSUE TITLE
Make GTK Entry box smaller

### ISSUE THREAD

**Issue by Art-2** [ib/xarchiver#59]
I find these entry boxes a little big:
Add files > Options > Encryption
![imagen](https://user-images.githubusercontent.com/12375357/39963047-2ddfe13a-561e-11e8-9af9-d95176338b75.png)

Action > Select by pattern 
![imagen](https://user-images.githubusercontent.com/12375357/39963049-4ade6de2-561e-11e8-8f70-64494c05846d.png)

**Comment by ib** [comment]
They sure are too big (on your system).

Please tell me about your system - especially the GTK version and theme you are using.

**Comment by Art-2** [comment]
sorry, I forgot to point it out:
Distro: Xubuntu 18.04
Desktop: Xfce 4.12.3
libgtk-3-0: 3.22.30

The theme is [Plano](https://github.com/lassekongo83/plano-theme) but it happen with Adwaita and [Greybird](https://github.com/shimmerproject/Greybird) too.

Maybe this helps?
[https://stackoverflow.com/questions/44866035/make-gtk-entry-box-smaller](https://stackoverflow.com/questions/44866035/make-gtk-entry-box-smaller)
