### ISSUE TITLE
Segfault when click some "Archive tree" entry during the load of a second tarball

### ISSUE THREAD

**Issue by daniloegea** [ib/xarchiver#60]
Xarchiver crashes if you click any file/folder in "Archive tree" while it's loading a second tarball.
In my case I opened one linux kernel tarball, opened a different linux tarball and while the second is loading I clicked on a folder in the Archive tree menu.

You can see some debug information here: https://gist.github.com/daniloegea/7800ec456a59f8b5ac89e85125973910

I opened two files, linux-4.17.tar.xz and linux-4.16.13.tar.xz. The archive struct has information about both for some reason. Lines [116](https://gist.github.com/daniloegea/7800ec456a59f8b5ac89e85125973910#file-gistfile1-txt-L116) and [119](https://gist.github.com/daniloegea/7800ec456a59f8b5ac89e85125973910#file-gistfile1-txt-L119).

I'm using FreeBSD.

**Comment by ib** [comment]
Fixed.
