### ISSUE TITLE
Preferences not persistant if xarchiverrc is absent

### ISSUE THREAD

**Issue by legends2k** [ib/xarchiver#62]
If `~/.config/xarchiver/xarchiverrc` is missing, defaults are loaded on launch as expected and they are shown in the _Preferences_ dialog.  Upon changing some option, pressing _OK_ and restarting the application, I see that the change isn't remembered.

When I do

```bash
$ touch ~/.config/xarchiver/xarchiverrc
```

and change some setting, I see that the changes are remembered on a application restart.

Irrespective of the presence of the config file, changes should be persisted across sessions i.e. if the file is missing, one should be created instead of not saving the preferences.

Here're the details of my installation

> xarchiver 0.5.4.13 (binary install through `pacman`)
> Xfce 4.12
> Archlinux

**Comment by ib** [comment]
Fixed.
