### ISSUE TITLE
Adding a "View" menu

### ISSUE THREAD

**Issue by Art-2** [ib/xarchiver#64]
Could a "View" menu be added to the menubar to quickly access the preferences of the window?
"Show archive location bar"
"Show archive tree sidebar"
"Show toolbar"

![imagen](https://user-images.githubusercontent.com/12375357/44315293-019f0280-a3e0-11e8-8daf-2aa5a0882033.png)

The following options could also be included:
"Cmd-line output"
"Archive comment"

**Comment by ib** [comment]
Unlikely.
