### ISSUE TITLE
Sort files by Date doesn't work as expected 

### ISSUE THREAD

**Issue by markHadman** [ib/xarchiver#65]
Months are sorted alphabetically rather than chronologically
![tmp](https://user-images.githubusercontent.com/34426238/44779494-87a51100-ab77-11e8-9840-5c1a95a1b0c5.png)

**Comment by ib** [comment]
I know. This is something on my to-do list. All the different date formats of the various archive types must be normalized. This will take some work.

**Comment by ib** [comment]
@markHadman 
Which archiver produced this output?

**Comment by ib** [comment]
Fixed.
