### ISSUE TITLE
Inflexible extraction behaviour

### ISSUE THREAD

**Issue by mirh** [ib/xarchiver#66]
- [ ] there doesn't seem to be any way to extract a folder inside an archive, dropping its root
- [ ] drag and drop extraction applies "last used" extraction preferences - when (*obviously?*) it should do the above always

**Comment by ib** [comment]
chang-zhao wrote:

> It's probably just correcting 1 line somewhere in the code?

Wrong guess (not even close). It was approx. 200 lines.

Finally realized.
