### ISSUE TITLE
[Suggestion] Add 'folder of archive' and 'current directory' as an option for 'Preferred extraction directory'

### ISSUE THREAD

**Issue by kuraga** [ib/xarchiver#68]
It would be very comfortable :)

**Comment by ib** [comment]
Please explain more detailed what this option should do.

**Comment by kuraga** [comment]
@ib, thanks for reply! Today we have a setting `Preferred extraction directory` (`/tmp` by default on my Calculate Linux) which can be set to any but concrete path. An archive will be extracted to that path (if I don't change extraction path).

I just want to have two new abilities:
1) To set `Preferred extraction directory` to `Current directory`. Archive will be extracted to `.` (`pwd`).
2) To set `Preferred extraction directory` to `Archive's folder`. Archive will be extracted to folder where the archive is.

Thanks!

**Comment by kuraga** [comment]
Ok, thanks!

**Comment by absolutelynothinghere** [comment]
`preferred_extract_dir=.` does not work as intended

**Comment by ib** [comment]
@absolutelynothinghere

What would you expect?

The "current directory" may change during program execution.

**Comment by absolutelynothinghere** [comment]
@ib I expected it to detect the directory but it just literally writes "." 

Can it at least auto-fill the directory that the archive is in (in the "Extract" dialog)?

**Comment by ib** [comment]
It already does so, if you delete `preferred_extract_dir` from `xarchiverrc`. (Currently, this only works as long as you have just one archive open at a time. I will improve this).

**Comment by ib** [comment]
@absolutelynothinghere

> I expected it to detect the directory but it just literally writes "."

I cannot reproduce. Extraction is done in the current directory.

**Comment by ib** [comment]
Leaving `preferred_extract_dir` in `xarchiverrc` empty (`preferred_extract_dir=`) or removing the entry there completely, will give you - as already before - the directory the archive is located in as suggested extraction directory.

This now applies to each opened archive individually.
