### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by kuraga** [ib/xarchiver#69]
Settings are not saved after xarchiver restarting in my 0.5.4.13 environment.

**Comment by kuraga** [comment]
Hm.....

```
sasha@node-calculate2 ~ $ echo $HOME
/home/sasha
sasha@node-calculate2 ~ $ ls -ld $HOME/.config
drwxr-xr-x 42 sasha sasha 4096 окт 22 22:05 /home/sasha/.config
sasha@node-calculate2 ~ $ ls -ld $HOME/.config/xarchiver
drwx------ 2 sasha sasha 4096 апр 24 22:49 /home/sasha/.config/xarchiver
sasha@node-calculate2 ~ $ ls -l $HOME/.config/xarchiver/xarchiverrc
ls: '/home/sasha/.config/xarchiver/xarchiverrc': No such file or directory 
```

`$HOME/.config/xarchiver` is empty.

**Comment by ib** [comment]
This is a bug that has been fixed in commit c8de88cf92aee851e64c99ddbacf938baba3d14d after the release of xarchiver 0.5.4.13.

You can fix it by ``` echo > /home/sasha/.config/xarchiver/xarchiverrc```. You'll start with empty settings then which can be set and saved from then on.

**Comment by kuraga** [comment]
Ok, thanks!

**Comment by kuraga** [comment]
P.S. Vote for 0.5.14.4 :smile:

**Comment by ib** [comment]
See issue #62.

**Comment by kuraga** [comment]
@ib I meant - let's release a new version!
