### ISSUE TITLE
Remove auto-generated content

### ISSUE THREAD

**Issue by City-busz** [ib/xarchiver#7]
I suggest to revert commit https://github.com/ib/xarchiver/commit/bb5fce0c7e0bd41fb64ea3acdf94577a773a6631 as these files are auto-generated, and no need to be tracked in git. Instead of that, if you want to provide configure script for the users, then I recommend make a package for each release with "make dist", [create a new release on GitHub](https://github.com/ib/xarchiver/releases/new), and upload the package. This is the way how other projects do this.

**Comment by ib** [comment]
I know that I'm tracking auto-generated files. I'm doing this deliberately.

I won't make other kind of releases than [tagging](https://github.com/ib/xarchiver/releases) and I want users to be able to configure and install without having to have autotools and stuff.
