### ISSUE TITLE
Extract multiple files via drag and drop

### ISSUE THREAD

**Issue by tanertas** [ib/xarchiver#72]
When I try to extract multiple selected files via drag and drop, xarchiver always discard selections and only operates with single file.

**Comment by lyghters** [comment]
That's really annoying for a gui-based archiver, is there any news about this?

**Comment by ib** [comment]
No, not yet.

It's on my to-do list.

**Comment by bxkx** [comment]
Hi, any news of this?

**Comment by ib** [comment]
No, not yet.

It's on my to-do list.

**Comment by tanertas** [comment]
> Xarchiver is the ultimate solution for handling archives on Linux and FreeBSD.

I guess handling multiple files doesn't count.

**Comment by delightfuldude** [comment]
+1
Any news on that issue? Extracting multiple files using drag and drop would be very appreciated!

**Comment by ib** [comment]
No, not yet.

It's on (top of) my to-do list.
