### ISSUE TITLE
An error has occurred when accessing the archive with MEGA zips

### ISSUE THREAD

**Issue by j-james** [ib/xarchiver#76]
Hello, 
When extracting some zip files, I've consistently been getting `An error has occurred when accessing the archive:` message with no other information.

[Image](https://i.imgur.com/VRbuj4W.png)

The extracted files don't seem to be damaged or anything, and I've made sure I'm downloading uncorrupted zips. After a little bit of testing, it seems to only be happening zips downloaded from mega.nz. 

How can I get more information about the error? It seems like it should appear in the popup box, but it doesn't...

Specs:
Manjaro Linux (i3) 18.0.4
Xarchiver 0.5.4.14

**Comment by ib** [comment]
The command line output popup box collects stderr output. It seems that there is none although there is an error return code. What program does your unzip (type `xarchiver -i` on a command line). A "defective" zip archive sample would be helpful.

**Comment by ib** [comment]
Closed for lack of response.
