### ISSUE TITLE
Crash after adding/removing a folder and clicking in the tree

### ISSUE THREAD

**Issue by kuraga** [ib/xarchiver#77]
Good day!

I've clicked at the last moments. Segmentation faults followed. Type of archive doesn't matter.

Same for 0.5.14.3.

![1](https://user-images.githubusercontent.com/1063219/55148825-0be56400-515a-11e9-9d74-e3f98078339b.gif)
![2](https://user-images.githubusercontent.com/1063219/55148827-0be56400-515a-11e9-9177-d2209196e8c5.gif)

**Comment by ib** [comment]
Fixed.

**Comment by kuraga** [comment]
Confirm: there are no crashes on both cases in 0.5.4.15. Tree is being rebuilt. Fixed. Thanks!
