### ISSUE TITLE
Nothing happened if I didn't set archive type

### ISSUE THREAD

**Issue by kuraga** [ib/xarchiver#79]
1. `xarchiver --compress=abc.txt`
2. Don't set archive type (do nothing)!
3. Click "Create".
4. Window disappears. There are no new archives nor errors.

**Comment by ib** [comment]
I actually can't click "Create", it's disabled.

Please provide information about xarchiver version, your distribution etc.

**Comment by kuraga** [comment]
0.5.4.14, Calculate Linux

**Comment by ib** [comment]
This seems to be a GTK+ 3 bug.

**Comment by kuraga** [comment]
@ib , more precise?

What does xarchiver do if archive type isn't set?

**Comment by ib** [comment]
Archive type must be set, and xarchiver is designed to not leave the type unset. This works for GTK+ 2, but unfortunately not for GTK+ 3 at the moment. It's a bug to be fixed, so for the moment, please set something.

**Comment by kuraga** [comment]
Is there a GTK issue?

**Comment by ib** [comment]
I can't tell since I haven't yet investigated.

**Comment by kuraga** [comment]
No.

But seems like my `preferred_format` option was broken (it was an integer greater than number of formats; I don't know why).

But removing config solved the problem.

Sorry about wasting your time...

**Comment by ib** [comment]
> But seems like my preferred_format option was broken (it was an integer greater than number of formats; I don't know why).

Even this must not confuse xarchiver and is to be fixed.

**Comment by kuraga** [comment]
@ib, `gtk_combo_box_get_active(GTK_COMBO_BOX(prefs_window->combo_prefered_format)) == -1` here: https://github.com/ib/xarchiver/blob/master/src/new_dialog.c#L182

**Comment by kuraga** [comment]
@ib, thoughts about _reasons_ of this situation. Could list of archive types change? Say, my preference has been `23` but list became shorter and `23` became incorrect?

**Comment by ib** [comment]
Yes, the list can change depending on your installed and deinstalled (un)compressor/(un)archiver command line programs. So xarchiver  must be aware of this.

**Comment by ib** [comment]
Fixed.

**Comment by kuraga** [comment]
Confirm: it's impossible to not set archive type in 0.5.4.15, fixed. Thanks!
