### ISSUE TITLE
alternate too to use unrar event the 7zip-rar wehen decompresing rar files

### ISSUE THREAD

**Issue by mckaygerhard** [ib/xarchiver#81]
i tested the current support for unar and are VERY BUGGY .. 

however.. i can see that xarchiver uses unrar as alternatives. seems falback to 7zip-rar ... i have alerady installed both 7zip-rar and unrar.. 7zip-rar raises an error..

**Comment by ib** [comment]
What archive type did you try to open?

What is your unar version (`unar -v`)?

What does `xarchiver -i` say?

**Comment by mckaygerhard** [comment]
i configured a live/build sid so due that the resultin live image was gone, sorry .. but you can assume lasted unar and archiver was 0.5.4.14 so commits that priority as unar at first option and later 7zip as falback are included..

unrar was installed due auto install as reccomends by package, sice notes that does not work, revised at package manager aptitude and then unninstal the ugly unar.. (that seems handle all the possible file types).. 

after uninstalll unar some of the compressed format works.. like rar 4.X formats (decompress only) inclusivelly with password.. dues seems falcbak to 7zip .. but for rar 5.X theres no working behaviour ... i test coupe of formats.. mostly works..  due i am building a live image with uefi support

**Comment by ib** [comment]
Sorry, but this is far too unspecific. I can't help without exact error descriptions.

If any archive type doesn't work, it's most likely due to a missing (un)compressor/(un)archiver. `xarchiver -i` will give you more information.

**Comment by mckaygerhard** [comment]
it only fails with rar types, rest falback good! xarchiver try to use  p7zip-rar event unrar when both are installed.. the exact error i give to you when i return to the office..

**Comment by ib** [comment]
Both rar and unrar take precedence over 7z and unar, and are able to handle both rar 4.X and rar 5.X format. 7z (unlike unar) should be able to do so as well.
