### ISSUE TITLE
build system fails due too high requirements

### ISSUE THREAD

**Issue by mckaygerhard** [ib/xarchiver#82]
when try to build lasted i got that errors:

```
./autogen.sh
Creating the build system... src/Makefile.am:5: compiling `7zip.c' with per-target flags requires `AM_PROG_CC_C_O' in `configure.ac'
configure.ac:24: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
       If this token and others are legitimate, please use m4_pattern_allow.
       See the Autoconf documentation.
```

Seems a too high requirement for gettex are in usage.. that leaks to older uses return to file-roller due older file-roller version works without problems with recent cupport for newer formats.. 

as recommendatios permits to build recent versin of xarchiver for older systems so then able to make transition to xarchiver without problems in funtionallity

tested in jessie and wheezy.. also try to build GTK2 verions in squeeze and lenny of Debian systems

**Comment by ib** [comment]
Do you need to call `autogen.sh`? Doesn't `./configure` work for you?

Since automake 1.14 , the AC_PROG_CC macro checks for per-target flags support (AM_PROG_CC_C_O) - and automake 1.14 is from 2013.

What version of autoconf, automake, gettext and libtool are you using?

**Comment by mckaygerhard** [comment]
i build a package for LFS and also Debian squeeze (gtk2), wheeze, jessie, strecht and buster and sid at same time! so i call `autoconf.sh` due the MULTIARCH and other stuffs.. `configure` does not work in those builds at same time and i need to build all of then in one shot due resources.. but fails in all except buster. 

take in consideration that its for "light" linux in older computers.. **xarchiver 0.5.4 builds fine with gtk2:** so **if i need to upgrade to newer linux .. that means that i cannot use older computer and if i need to buy a 1000$ computer (then), so then i sue gnome/kde/qt archiver file-roller** or wors.. i use windows.. so its nonsense tell me "upgraded"

autoconf -> 2.58 as minimun
automake -> 1.13 as minimum
gettext .> 0.18+

**Comment by ib** [comment]
> autoconf -> 2.58 as minimun
> automake -> 1.13 as minimum

This doesn't seem to make sense.
Automake 1.13 requires autoconf 2.65, and it defines AC_CONFIG_MACRO_DIRS.
What exact versions of autoconf, automake, libtool, intltool, gettext, glib and pkg-config did you use?
