### ISSUE TITLE
Store archiver output should store the command as well

### ISSUE THREAD

**Issue by PMunch** [ib/xarchiver#83]
I ran into an issue with .rar files under Xarchiver. I can extract the contents of the file fine with `rar x <filename>`, and I can open the file in Xarchiver to list the content, but trying to double click a file, or do any extraction apart from extract all ends with an error:
```
RAR 5.71   Copyright (c) 1993-2019 Alexander Roshal   28 Apr 2019
Trial version             Type 'rar -?' for help


Extracting from <filename>

No files to extract
```
It would be nice to be able to see what the actual command that was run is in this window, so I could try and figure out why it fails.

**Comment by ib** [comment]
Does <filename> contain non-ASCII characters?

**Comment by PMunch** [comment]
No, it's only ASCII characters

**Comment by ib** [comment]
Does it contain a dash (ASCII 0x2D)?

What encoding is your file system in? What is your locale (LC_ALL)?

**Comment by PMunch** [comment]
No, neither the archive name, nor the file in it contains a dash in the name.

The file system is ext4, but it was created from a Windows machine. The locale is blank.

**Comment by ib** [comment]
Done.
