### ISSUE TITLE
Strange behavior on some archives

### ISSUE THREAD

**Issue by vlig** [ib/xarchiver#84]
It shows uncorrect archive tree and no able to unarchive.
For example [this](https://store.kde.org/p/1166289/startdownload?file_id=1566020634&file_name=papirus-icon-theme-20190817.tar.xz&file_type=application/x-xz&file_size=12090508) archive it shows like:
![xarchiver](https://user-images.githubusercontent.com/19915584/63217622-255f6a80-c152-11e9-9e51-53bcf162a78e.png)
And unarchived with tar:
![unarchived](https://user-images.githubusercontent.com/19915584/63217609-c39f0080-c151-11e9-87cc-4b78276f6672.png)
Desktop: FreeBSD 12.0 RELEASE + LXQt up to date, xarchiver 0.5.4.7.

**Comment by ib** [comment]
You should upgrade to latest xarchiver. Version 0.5.4.7 is three years old.

**Comment by vlig** [comment]
In FreeBSD packages and ports there is only 0.5.4.7, unfortunately... Thanks! I guess I need to build it for myself...

**Comment by ib** [comment]
I actually don't remember such an xarchiver bug, so it might be your `tar` as well. Which is it?

**Comment by vlig** [comment]
```
tar --version
bsdtar 3.3.3 - libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.7
```
tar works good, no such bugs.
Some compile errors on make install, I'll maybe open another issue.

**Comment by ib** [comment]
I'm pretty sure it's because of `bsdtar`. Is there a GNU tar named `gtar` in FreeBSD? If so, please install and try again.

**Comment by ib** [comment]
BTW, I'd be interested in the build errors in order to fix them for FreeBSD.

**Comment by vlig** [comment]
Sorry for long delay. Here is my console output right after git clone and cd into it. I still cannot build it.
https://pastebin.com/1swkaWdH

**Comment by ib** [comment]
The le32toh error should be fixed in master.

Did you see my comment on `gtar` from Sep 11th?

**Comment by vlig** [comment]
Installing `gtar` did the trick! So, looks like `xarchiver` are unfriendly with `bsdtar`.
I never would have thought that there were [tangible differences](https://unix.stackexchange.com/a/167199) between them.

**Comment by ib** [comment]
xarchiver gets built, but I don't know why the FreeBSD `make` (bmake?) doesn't find the rule for xarchiver.desktop. It doesn't build anything in the po directory either.

**Comment by vlig** [comment]
Unfortunately, I'm not coder, so I can only give you this link:
https://www.freebsd.org/doc/en_US.ISO8859-1/books/developers-handbook/index.html
I think it is enough for coder for build process understanding in FreeBSD.

**Comment by ib** [comment]
It's most likely not  a problem with the FreeBSD build process itself, but with the FreeBSD `make`.
Could you please try to install GNU make (`gmake`) and try again with gmake?

**Comment by vlig** [comment]
You're right, it builds and installs with `gmake`. So, for now BSD-ones need to install some Linux related stuff just to run it... By the way, opening archive from first post taking too long time - is about 30 s, is it OK? X230 laptop, i5 CPU, 8G. `(g)tar` opens it in console with zero latency.
(Also, there is poor translation on my native language...)

**Comment by ib** [comment]
Thanks for trying out.

Support for bsdtar is on my list, but unfortunately bsdtar lacks a few options.

Slow opening of big archives is a known issue, it's also on my list. 

You're welcome to revise the translation (please see #73).
