### ISSUE TITLE
[ENH] Show progress dialog on command line compress

### ISSUE THREAD

**Issue by kuraga** [ib/xarchiver#87]
`xarchiver --compress` doesn't show progress dialog.

(BTW, am I right? I remembered it was in the past, wasn't it?)

Proposition: show progress dialog on command line compress.

**Comment by ib** [comment]
As far as I remember, there never was one. After entering the name of the archive, the files will be compressed in a single step with a background command. There is no feedback until the process has finished.

**Comment by kuraga** [comment]
@ib I talk about not bar but dialog/window. On decompress, we see a window with "percentless progress bar". On compress, I don't see. But I saw in previous versions, I remember.

**Comment by ib** [comment]
Okay, now I see.

**Comment by ib** [comment]
Fixed.

**Comment by kuraga** [comment]
Confirm: fixed in 0.5.4.15. Thanks!
