### ISSUE TITLE
Be able to set compression options

### ISSUE THREAD

**Issue by lululock71** [ib/xarchiver#91]
Hi, I'm using xarchiver for a while but something's missing in my opinion or I don't know how to get such option: 
Is there a way to set compression options in xarchiver, other than just choose which compression method to use ? I assume xarchiver uses the default settings for each archive type.

If there's no way yet, I suggest to add some option where we can give additional arguments to pass to the compression tool, so at least advanced users could have custom settings.

**Comment by ib** [comment]
Add files > Options > Compression

**Comment by lululock71** [comment]
There's no settings for dictionary sizes, etc... here. It just sets the basics.

**Comment by ib** [comment]
What do you mean by "settings for dictionary sizes"?
You can set the compression level.
