### ISSUE TITLE
DISPLAY environment variable is overriden by WAYLAND_DISPLAY value

### ISSUE THREAD

**Issue by Exagone313** [ib/xarchiver#96]
Hi,

I noticed that programs opened via xarchiver in Wayland got the `DISPLAY` environment replaced by `WAYLAND_DISPLAY` value.

## Steps to reproduce

* Open a Wayland session, e.g. with sway
* Replace `xdg-open` in your `PATH` by a script that runs a command (redirected to a file), such as below
* Open an archive with *xarchiver*

```bash
#!/bin/sh
env | grep DISPLAY | sort > /tmp/xdg-open.txt
```

## Actual result

`DISPLAY` environment variable is wrongly overridden, preventing XWayland applications to run.

```
DISPLAY=wayland-0
WAYLAND_DISPLAY=wayland-0
```

## Expected result

`DISPLAY` environment variable is left untouched.

```
DISPLAY=:0
WAYLAND_DISPLAY=wayland-0
```

## In the code

I haven't looked at the underlying logic/reasoning, but I found where it is overridden:
https://github.com/ib/xarchiver/blob/51903bd0a6262f9abe85dd1ded97ce54aa58f173/src/window.c#L488
https://github.com/ib/xarchiver/blob/51903bd0a6262f9abe85dd1ded97ce54aa58f173/src/window.c#L2394

**Comment by Exagone313** [comment]
I added a workaround script in my `PATH` for now:
```bash
#!/bin/sh
if [ -n "$WAYLAND_DISPLAY" ]; then
	# fix xarchiver bug that override DISPLAY to WAYLAND_DISPLAY content
	export DISPLAY=:0
fi
exec /usr/bin/xdg-open "$@"
```

**Comment by Exagone313** [comment]
https://developer.gnome.org/gdk3/stable/GdkScreen.html#gdk-screen-make-display-name
> `gdk_screen_make_display_name` has been deprecated since version 3.22 and should not be used in newly-written code.
I think I'm going to create a pull request that removes that call.

**Comment by ib** [comment]
This doesn't seem to work when starting xarchiver e.g. on :0 with option `--display :0.1` on a second screen. The programs run on :0 instead of :0.1 then.

I don't use Wayland. Could you please test if the attached patch fixes the issue?

[#96.zip](https://github.com/ib/xarchiver/files/4751140/96.zip)

**Comment by Exagone313** [comment]
I didn't check if it works but it surely does, but it's hacky.

It should be better to check what is idiomatic in GTK+ for handling custom displays. There shouldn't be a need for a code specifically for Wayland as GTK+ is supposed to support Wayland 🤔

But like said above, the code uses deprecated functions that could be removed in the future (GTK+ 4 for example?).

**Comment by ib** [comment]
@Exagone313 
> I didn't check if it works but it surely does

Well, thanks for you _support_ then.

**Comment by Exagone313** [comment]
I'm sorry about this.
